        byte    "AMD",0'             AMD
        byte    "AMI               ",0'             AMI
        byte    "Fairchild               ",0'             Fairchild
        byte    "Fujitsu               ",0'             Fujitsu
        byte    "GTE               ",0'             GTE
        byte    "Harris               ",0'             Harris
        byte    "Hitachi",0'             Hitachi
        byte    "Inmos",0'             Inmos
        byte    "Intel",0'             Intel
        byte    "I.T.T.",0'             I.T.T.
        byte    "Intersil",0'             Intersil
        byte    "Monolithic Memor",0'             Monolithic Memories           
        byte    "Mostek",0'             Mostek
        byte    "Freescale (Motor",0'             Freescale (Motorola)           
        byte    "National",0'             National
        byte    "NEC",0'             NEC
        byte    "RCA",0'             RCA
        byte    "Raytheon",0'             Raytheon
        byte    "Synaptics",0'             Synaptics    
        byte    "Seeq",0'             Seeq
        byte    "NXP (Philips)",0'             NXP (Philips)
        byte    "Synertek",0'             Synertek
        byte    "Texas Instrument",0'             Texas Instruments           
        byte    "Kioxia Corporati",0'             Kioxia Corporation           
        byte    "Xicor",0'             Xicor
        byte    "Zilog",0'             Zilog
        byte    "Eurotechnique",0'             Eurotechnique
        byte    "Mitsubishi",0'             Mitsubishi
        byte    "Lucent (AT&T)",0'             Lucent (AT&T)
        byte    "Exel",0'             Exel
        byte    "Atmel",0'             Atmel
        byte    "STMicroelectroni",0'             STMicroelectronics           
        byte    "Lattice Semi.",0'             Lattice Semi.
        byte    "NCR",0'             NCR
        byte    "Wafer Scale Inte",0'             Wafer Scale Integration           
        byte    "IBM",0'             IBM
        byte    "Tristar",0'             Tristar
        byte    "Visic",0'             Visic
        byte    "Intl. CMOS Techn",0'             Intl. CMOS Technology           
        byte    "SSSI",0'             SSSI
        byte    "Microchip Techno",0'             Microchip Technology           
        byte    "Ricoh Ltd",0'             Ricoh Ltd
        byte    "VLSI",0'             VLSI
        byte    "Micron Technolog",0'             Micron Technology           
        byte    "SK Hynix",0'             SK Hynix
        byte    "OKI Semiconducto",0'             OKI Semiconductor           
        byte    "ACTEL",0'             ACTEL
        byte    "Sharp",0'             Sharp
        byte    "Catalyst",0'             Catalyst
        byte    "Panasonic",0'             Panasonic
        byte    "IDT",0'             IDT
        byte    "Cypress",0'             Cypress
        byte    "DEC",0'             DEC
        byte    "LSI Logic",0'             LSI Logic
        byte    "Zarlink (Plessey",0'             Zarlink (Plessey)           
        byte    "UTMC",0'             UTMC
        byte    "Thinking Machine",0'             Thinking Machine
        byte    "Thomson CSF",0'             Thomson CSF
        byte    "Integrated CMOS ",0'             Integrated CMOS (Vertex)           
        byte    "Honeywell",0'             Honeywell
        byte    "Tektronix",0'             Tektronix
        byte    "Oracle Corporati",0'             Oracle Corporation           
        byte    "Silicon Storage ",0'             Silicon Storage Technology           
        byte    "ProMos/Mosel Vit",0'             ProMos/Mosel Vitelic           
        byte    "Infineon (Siemen",0'             Infineon (Siemens)           
        byte    "Macronix",0'             Macronix
        byte    "Xerox",0'             Xerox
        byte    "Plus Logic",0'             Plus Logic
        byte    "Western Digital ",0'             Western Digital Technologies Inc           
        byte    "Elan Circuit Tec",0'             Elan Circuit Tech.           
        byte    "European Silicon",0'             European Silicon Str.           
        byte    "Apple Computer",0'             Apple Computer
        byte    "Xilinx",0'             Xilinx
        byte    "Compaq",0'             Compaq
        byte    "Protocol Engines",0'             Protocol Engines
        byte    "SCI",0'             SCI
        byte    "ABLIC",0'             ABLIC
        byte    "Samsung",0'             Samsung
        byte    "I3 Design System",0'             I3 Design System
        byte    "Klic",0'             Klic
        byte    "Crosspoint Solut",0'             Crosspoint Solutions           
        byte    "Alliance Memory ",0'             Alliance Memory Inc           
        byte    "Tandem",0'             Tandem
        byte    "Hewlett-Packard",0'             Hewlett-Packard
        byte    "Integrated Silic",0'             Integrated Silicon Solutions           
        byte    "Brooktree",0'             Brooktree
        byte    "New Media",0'             New Media
        byte    "MHS Electronic",0'             MHS Electronic
        byte    "Performance Semi",0'             Performance Semi.           
        byte    "Winbond Electron",0'             Winbond Electronic           
        byte    "Kawasaki Steel",0'             Kawasaki Steel
        byte    "Bright Micro",0'             Bright Micro
        byte    "TECMAR",0'             TECMAR
        byte    "Exar",0'             Exar
        byte    "PCMCIA",0'             PCMCIA
        byte    "LG Semi (Goldsta",0'             LG Semi (Goldstar)           
        byte    "Northern Telecom",0'             Northern Telecom
        byte    "Sanyo",0'             Sanyo
        byte    "Array Microsyste",0'             Array Microsystems           
        byte    "Crystal Semicond",0'             Crystal Semiconductor           
        byte    "Analog Devices",0'             Analog Devices
        byte    "PMC-Sierra",0'             PMC-Sierra
        byte    "Asparix",0'             Asparix
        byte    "Convex Computer",0'             Convex Computer
        byte    "Quality Semicond",0'             Quality Semiconductor           
        byte    "Nimbus Technolog",0'             Nimbus Technology           
        byte    "Transwitch",0'             Transwitch
        byte    "Micronas (ITT In",0'             Micronas (ITT Intermetall)           
        byte    "Cannon",0'             Cannon
        byte    "Altera",0'             Altera
        byte    "NEXCOM",0'             NEXCOM
        byte    "Qualcomm",0'             Qualcomm
        byte    "Sony",0'             Sony
        byte    "Cray Research",0'             Cray Research
        byte    "AMS(Austria Micr",0'             AMS(Austria Micro)           
        byte    "Vitesse",0'             Vitesse
        byte    "Aster Electronic",0'             Aster Electronics           
        byte    "Bay Networks (Sy",0'             Bay Networks (Synoptic)           
        byte    "Zentrum/ZMD",0'             Zentrum/ZMD
        byte    "TRW",0'             TRW
        byte    "Thesys",0'             Thesys
        byte    "Solbourne Comput",0'             Solbourne Computer           
        byte    "Allied-Signal",0'             Allied-Signal
        byte    "Dialog Semicondu",0'             Dialog Semiconductor           
        byte    "Media Vision",0'             Media Vision
        byte    "Numonyx Corporat",0'             Numonyx Corporation           
        byte    "Cirrus Logic",0'             Cirrus Logic
        byte    "National Instrum",0'             National Instruments           
        byte    "ILC Data Device",0'             ILC Data Device
        byte    "Alcatel Mietec",0'             Alcatel Mietec
        byte    "Micro Linear",0'             Micro Linear
        byte    "Univ. of NC",0'             Univ. of NC
        byte    "JTAG Technologie",0'             JTAG Technologies           
        byte    "BAE Systems (Lor",0'             BAE Systems (Loral)           
        byte    "Nchip",0'             Nchip
        byte    "Galileo Tech",0'             Galileo Tech
        byte    "Bestlink Systems",0'             Bestlink Systems
        byte    "Graychip",0'             Graychip
        byte    "GENNUM",0'             GENNUM
        byte    "Imagination Tech",0'             Imagination Technologies Limited           
        byte    "Robert Bosch",0'             Robert Bosch
        byte    "Chip Express",0'             Chip Express
        byte    "DATARAM",0'             DATARAM
        byte    "United Microelec",0'             United Microelectronics Corp           
        byte    "TCSI",0'             TCSI
        byte    "Smart Modular",0'             Smart Modular
        byte    "Hughes Aircraft",0'             Hughes Aircraft
        byte    "Lanstar Semicond",0'             Lanstar Semiconductor           
        byte    "Qlogic",0'             Qlogic
        byte    "Kingston",0'             Kingston
        byte    "Music Semi",0'             Music Semi
        byte    "Ericsson Compone",0'             Ericsson Components           
        byte    "SpaSE",0'             SpaSE
        byte    "Eon Silicon Devi",0'             Eon Silicon Devices           
        byte    "Integrated Silic",0'             Integrated Silicon Solution (ISSI)           
        byte    "DoD",0'             DoD
        byte    "Integ. Memories ",0'             Integ. Memories Tech.           
        byte    "Corollary Inc",0'             Corollary Inc
        byte    "Dallas Semicondu",0'             Dallas Semiconductor           
        byte    "Omnivision",0'             Omnivision
        byte    "EIV(Switzerland)",0'             EIV(Switzerland)
        byte    "Novatel Wireless",0'             Novatel Wireless
        byte    "Zarlink (Mitel)",0'             Zarlink (Mitel)
        byte    "Clearpoint",0'             Clearpoint
        byte    "Cabletron",0'             Cabletron
        byte    "STEC (Silicon Te",0'             STEC (Silicon Tech)           
        byte    "Vanguard",0'             Vanguard
        byte    "Hagiwara Sys-Com",0'             Hagiwara Sys-Com
        byte    "Vantis",0'             Vantis
        byte    "Celestica",0'             Celestica
        byte    "Century",0'             Century
        byte    "Hal Computers",0'             Hal Computers
        byte    "Rohm Company Ltd",0'             Rohm Company Ltd
        byte    "Juniper Networks",0'             Juniper Networks
        byte    "Libit Signal Pro",0'             Libit Signal Processing           
        byte    "Mushkin Enhanced",0'             Mushkin Enhanced Memory           
        byte    "Tundra Semicondu",0'             Tundra Semiconductor           
        byte    "Adaptec Inc",0'             Adaptec Inc
        byte    "LightSpeed Semi.",0'             LightSpeed Semi.
        byte    "ZSP Corp",0'             ZSP Corp
        byte    "AMIC Technology",0'             AMIC Technology
        byte    "Adobe Systems",0'             Adobe Systems
        byte    "Dynachip",0'             Dynachip
        byte    "PNY Technologies",0'             PNY Technologies Inc           
        byte    "Newport Digital",0'             Newport Digital
        byte    "MMC Networks",0'             MMC Networks
        byte    "T Square",0'             T Square
        byte    "Seiko Epson",0'             Seiko Epson
        byte    "Broadcom",0'             Broadcom
        byte    "Viking Component",0'             Viking Components           
        byte    "V3 Semiconductor",0'             V3 Semiconductor
        byte    "Flextronics (Orb",0'             Flextronics (Orbit Semiconductor)           
        byte    "Suwa Electronics",0'             Suwa Electronics
        byte    "Transmeta",0'             Transmeta
        byte    "Micron CMS",0'             Micron CMS
        byte    "American Compute",0'             American Computer & Digital Components Inc           
        byte    "Enhance 3000 Inc",0'             Enhance 3000 Inc
        byte    "Tower Semiconduc",0'             Tower Semiconductor           
        byte    "CPU Design",0'             CPU Design
        byte    "Price Point",0'             Price Point
        byte    "Maxim Integrated",0'             Maxim Integrated Product           
        byte    "Tellabs",0'             Tellabs
        byte    "Centaur Technolo",0'             Centaur Technology           
        byte    "Unigen Corporati",0'             Unigen Corporation           
        byte    "Transcend Inform",0'             Transcend Information           
        byte    "Memory Card Tech",0'             Memory Card Technology           
        byte    "CKD Corporation ",0'             CKD Corporation Ltd           
        byte    "Capital Instrume",0'             Capital Instruments Inc           
        byte    "Aica Kogyo Ltd",0'             Aica Kogyo Ltd
        byte    "Linvex Technolog",0'             Linvex Technology           
        byte    "MSC Vertriebs Gm",0'             MSC Vertriebs GmbH           
        byte    "AKM Company Ltd",0'             AKM Company Ltd
        byte    "Dynamem Inc",0'             Dynamem Inc
        byte    "NERA ASA",0'             NERA ASA
        byte    "GSI Technology",0'             GSI Technology
        byte    "Dane-Elec (C Mem",0'             Dane-Elec (C Memory)           
        byte    "Acorn Computers",0'             Acorn Computers
        byte    "Lara Technology",0'             Lara Technology
        byte    "Oak Technology I",0'             Oak Technology Inc           
        byte    "Itec Memory",0'             Itec Memory
        byte    "Tanisys Technolo",0'             Tanisys Technology           
        byte    "Truevision",0'             Truevision
        byte    "Wintec Industrie",0'             Wintec Industries           
        byte    "Super PC Memory",0'             Super PC Memory
        byte    "MGV Memory",0'             MGV Memory
        byte    "Galvantech",0'             Galvantech
        byte    "Gadzoox Networks",0'             Gadzoox Networks
        byte    "Multi Dimensiona",0'             Multi Dimensional Cons.           
        byte    "GateField",0'             GateField
        byte    "Integrated Memor",0'             Integrated Memory System           
        byte    "Triscend",0'             Triscend
        byte    "XaQti",0'             XaQti
        byte    "Goldenram",0'             Goldenram
        byte    "Clear Logic",0'             Clear Logic
        byte    "Cimaron Communic",0'             Cimaron Communications           
        byte    "Nippon Steel Sem",0'             Nippon Steel Semi. Corp           
        byte    "Advantage Memory",0'             Advantage Memory
        byte    "AMCC",0'             AMCC
        byte    "LeCroy",0'             LeCroy
        byte    "Yamaha Corporati",0'             Yamaha Corporation           
        byte    "Digital Microwav",0'             Digital Microwave           
        byte    "NetLogic Microsy",0'             NetLogic Microsystems           
        byte    "MIMOS Semiconduc",0'             MIMOS Semiconductor           
        byte    "Advanced Fibre",0'             Advanced Fibre
        byte    "BF Goodrich Data",0'             BF Goodrich Data.           
        byte    "Epigram",0'             Epigram
        byte    "Acbel Polytech I",0'             Acbel Polytech Inc           
        byte    "Apacer Technolog",0'             Apacer Technology           
        byte    "Admor Memory",0'             Admor Memory
        byte    "FOXCONN",0'             FOXCONN
        byte    "Quadratics Super",0'             Quadratics Superconductor           
        byte    "3COM",0'             3COM
        byte    "Camintonn Corpor",0'             Camintonn Corporation           
        byte    "ISOA Incorporate",0'             ISOA Incorporated           
        byte    "Agate Semiconduc",0'             Agate Semiconductor           
        byte    "ADMtek Incorpora",0'             ADMtek Incorporated           
        byte    "HYPERTEC",0'             HYPERTEC
        byte    "Adhoc Technologi",0'             Adhoc Technologies           
        byte    "MOSAID Technolog",0'             MOSAID Technologies           
        byte    "Ardent Technolog",0'             Ardent Technologies           
        byte    "Switchcore",0'             Switchcore
        byte    "Cisco Systems In",0'             Cisco Systems Inc           
        byte    "Allayer Technolo",0'             Allayer Technologies           
        byte    "WorkX AG (Wichma",0'             WorkX AG (Wichman)           
        byte    "Oasis Semiconduc",0'             Oasis Semiconductor           
        byte    "Novanet Semicond",0'             Novanet Semiconductor           
        byte    "E-M Solutions",0'             E-M Solutions
        byte    "Power General",0'             Power General
        byte    "Advanced Hardwar",0'             Advanced Hardware Arch.           
        byte    "Inova Semiconduc",0'             Inova Semiconductors GmbH           
        byte    "Telocity",0'             Telocity
        byte    "Delkin Devices",0'             Delkin Devices
        byte    "Symagery Microsy",0'             Symagery Microsystems           
        byte    "C-Port Corporati",0'             C-Port Corporation           
        byte    "SiberCore Techno",0'             SiberCore Technologies           
        byte    "Southland Micros",0'             Southland Microsystems           
        byte    "Malleable Techno",0'             Malleable Technologies           
        byte    "Kendin Communica",0'             Kendin Communications           
        byte    "Great Technology",0'             Great Technology Microcomputer           
        byte    "Sanmina Corporat",0'             Sanmina Corporation           
        byte    "HADCO Corporatio",0'             HADCO Corporation           
        byte    "Corsair",0'             Corsair
        byte    "Actrans System I",0'             Actrans System Inc           
        byte    "ALPHA Technologi",0'             ALPHA Technologies           
        byte    "Silicon Laborato",0'             Silicon Laboratories Inc (Cygnal)           
        byte    "Artesyn Technolo",0'             Artesyn Technologies           
        byte    "Align Manufactur",0'             Align Manufacturing           
        byte    "Peregrine Semico",0'             Peregrine Semiconductor           
        byte    "Chameleon System",0'             Chameleon Systems           
        byte    "Aplus Flash Tech",0'             Aplus Flash Technology           
        byte    "MIPS Technologie",0'             MIPS Technologies           
        byte    "Chrysalis ITS",0'             Chrysalis ITS
        byte    "ADTEC Corporatio",0'             ADTEC Corporation           
        byte    "Kentron Technolo",0'             Kentron Technologies           
        byte    "Win Technologies",0'             Win Technologies
        byte    "Tezzaron Semicon",0'             Tezzaron Semiconductor           
        byte    "Extreme Packet D",0'             Extreme Packet Devices           
        byte    "RF Micro Devices",0'             RF Micro Devices
        byte    "Siemens AG",0'             Siemens AG
        byte    "Sarnoff Corporat",0'             Sarnoff Corporation           
        byte    "Itautec SA",0'             Itautec SA
        byte    "Radiata Inc",0'             Radiata Inc
        byte    "Benchmark Elect.",0'             Benchmark Elect. (AVEX)           
        byte    "Legend",0'             Legend
        byte    "SpecTek Incorpor",0'             SpecTek Incorporated           
        byte    "Hi/fn",0'             Hi/fn
        byte    "Enikia Incorpora",0'             Enikia Incorporated           
        byte    "SwitchOn Network",0'             SwitchOn Networks           
        byte    "AANetcom Incorpo",0'             AANetcom Incorporated           
        byte    "Micro Memory Ban",0'             Micro Memory Bank           
        byte    "ESS Technology",0'             ESS Technology
        byte    "Virata Corporati",0'             Virata Corporation           
        byte    "Excess Bandwidth",0'             Excess Bandwidth
        byte    "West Bay Semicon",0'             West Bay Semiconductor           
        byte    "DSP Group",0'             DSP Group
        byte    "Newport Communic",0'             Newport Communications           
        byte    "Chip2Chip Incorp",0'             Chip2Chip Incorporated           
        byte    "Phobos Corporati",0'             Phobos Corporation           
        byte    "Intellitech Corp",0'             Intellitech Corporation           
        byte    "Nordic VLSI ASA",0'             Nordic VLSI ASA
        byte    "Ishoni Networks",0'             Ishoni Networks
        byte    "Silicon Spice",0'             Silicon Spice
        byte    "Alchemy Semicond",0'             Alchemy Semiconductor           
        byte    "Agilent Technolo",0'             Agilent Technologies           
        byte    "Centillium Commu",0'             Centillium Communications           
        byte    "W.L. Gore",0'             W.L. Gore
        byte    "HanBit Electroni",0'             HanBit Electronics           
        byte    "GlobeSpan",0'             GlobeSpan
        byte    "Element 14",0'             Element 14
        byte    "Pycon",0'             Pycon
        byte    "Saifun Semicondu",0'             Saifun Semiconductors           
        byte    "Sibyte Incorpora",0'             Sibyte Incorporated           
        byte    "MetaLink Technol",0'             MetaLink Technologies           
        byte    "Feiya Technology",0'             Feiya Technology
        byte    "I & C Technology",0'             I & C Technology
        byte    "Shikatronics",0'             Shikatronics
        byte    "Elektrobit",0'             Elektrobit
        byte    "Megic",0'             Megic
        byte    "Com-Tier",0'             Com-Tier
        byte    "Malaysia Micro S",0'             Malaysia Micro Solutions           
        byte    "Hyperchip",0'             Hyperchip
        byte    "Gemstone Communi",0'             Gemstone Communications           
        byte    "Anadigm (Anadyne",0'             Anadigm (Anadyne)           
        byte    "3ParData",0'             3ParData
        byte    "Mellanox Technol",0'             Mellanox Technologies           
        byte    "Tenx Technologie",0'             Tenx Technologies           
        byte    "Helix AG",0'             Helix AG
        byte    "Domosys",0'             Domosys
        byte    "Skyup Technology",0'             Skyup Technology
        byte    "HiNT Corporation",0'             HiNT Corporation
        byte    "Chiaro",0'             Chiaro
        byte    "MDT Technologies",0'             MDT Technologies GmbH           
        byte    "Exbit Technology",0'             Exbit Technology A/S           
        byte    "Integrated Techn",0'             Integrated Technology Express           
        byte    "AVED Memory",0'             AVED Memory
        byte    "Legerity",0'             Legerity
        byte    "Jasmine Networks",0'             Jasmine Networks
        byte    "Caspian Networks",0'             Caspian Networks
        byte    "nCUBE",0'             nCUBE
        byte    "Silicon Access N",0'             Silicon Access Networks           
        byte    "FDK Corporation",0'             FDK Corporation
        byte    "High Bandwidth A",0'             High Bandwidth Access           
        byte    "MultiLink Techno",0'             MultiLink Technology           
        byte    "BRECIS",0'             BRECIS
        byte    "World Wide Packe",0'             World Wide Packets           
        byte    "APW",0'             APW
        byte    "Chicory Systems",0'             Chicory Systems
        byte    "Xstream Logic",0'             Xstream Logic
        byte    "Fast-Chip",0'             Fast-Chip
        byte    "Zucotto Wireless",0'             Zucotto Wireless
        byte    "Realchip",0'             Realchip
        byte    "Galaxy Power",0'             Galaxy Power
        byte    "eSilicon",0'             eSilicon
        byte    "Morphics Technol",0'             Morphics Technology           
        byte    "Accelerant Netwo",0'             Accelerant Networks           
        byte    "Silicon Wave",0'             Silicon Wave
        byte    "SandCraft",0'             SandCraft
        byte    "Elpida",0'             Elpida
        byte    "Solectron",0'             Solectron
        byte    "Optosys Technolo",0'             Optosys Technologies           
        byte    "Buffalo (Formerl",0'             Buffalo (Formerly Melco)           
        byte    "TriMedia Technol",0'             TriMedia Technologies           
        byte    "Cyan Technologie",0'             Cyan Technologies           
        byte    "Global Locate",0'             Global Locate
        byte    "Optillion",0'             Optillion
        byte    "Terago Communica",0'             Terago Communications           
        byte    "Ikanos Communica",0'             Ikanos Communications           
        byte    "Princeton Techno",0'             Princeton Technology           
        byte    "Nanya Technology",0'             Nanya Technology
        byte    "Elite Flash Stor",0'             Elite Flash Storage           
        byte    "Mysticom",0'             Mysticom
        byte    "LightSand Commun",0'             LightSand Communications           
        byte    "ATI Technologies",0'             ATI Technologies
        byte    "Agere Systems",0'             Agere Systems
        byte    "NeoMagic",0'             NeoMagic
        byte    "AuroraNetics",0'             AuroraNetics
        byte    "Golden Empire",0'             Golden Empire
        byte    "Mushkin",0'             Mushkin
        byte    "Tioga Technologi",0'             Tioga Technologies           
        byte    "Netlist",0'             Netlist
        byte    "TeraLogic",0'             TeraLogic
        byte    "Cicada Semicondu",0'             Cicada Semiconductor           
        byte    "Centon Electroni",0'             Centon Electronics           
        byte    "Tyco Electronics",0'             Tyco Electronics
        byte    "Magis Works",0'             Magis Works
        byte    "Zettacom",0'             Zettacom
        byte    "Cogency Semicond",0'             Cogency Semiconductor           
        byte    "Chipcon AS",0'             Chipcon AS
        byte    "Aspex Technology",0'             Aspex Technology
        byte    "F5 Networks",0'             F5 Networks
        byte    "Programmable Sil",0'             Programmable Silicon Solutions           
        byte    "ChipWrights",0'             ChipWrights
        byte    "Acorn Networks",0'             Acorn Networks
        byte    "Quicklogic",0'             Quicklogic
        byte    "Kingmax Semicond",0'             Kingmax Semiconductor           
        byte    "BOPS",0'             BOPS
        byte    "Flasys",0'             Flasys
        byte    "BitBlitz Communi",0'             BitBlitz Communications           
        byte    "eMemory Technolo",0'             eMemory Technology           
        byte    "Procket Networks",0'             Procket Networks
        byte    "Purple Ray",0'             Purple Ray
        byte    "Trebia Networks",0'             Trebia Networks
        byte    "Delta Electronic",0'             Delta Electronics           
        byte    "Onex Communicati",0'             Onex Communications           
        byte    "Ample Communicat",0'             Ample Communications           
        byte    "Memory Experts I",0'             Memory Experts Intl           
        byte    "Astute Networks",0'             Astute Networks
        byte    "Azanda Network D",0'             Azanda Network Devices           
        byte    "Dibcom",0'             Dibcom
        byte    "Tekmos",0'             Tekmos
        byte    "API NetWorks",0'             API NetWorks
        byte    "Bay Microsystems",0'             Bay Microsystems
        byte    "Firecron Ltd",0'             Firecron Ltd
        byte    "Resonext Communi",0'             Resonext Communications           
        byte    "Tachys Technolog",0'             Tachys Technologies           
        byte    "Equator Technolo",0'             Equator Technology           
        byte    "Concept Computer",0'             Concept Computer
        byte    "SILCOM",0'             SILCOM
        byte    "3Dlabs",0'             3Dlabs
        byte    "c't Magazine",0'             c't Magazine
        byte    "Sanera Systems",0'             Sanera Systems
        byte    "Silicon Packets",0'             Silicon Packets
        byte    "Viasystems Group",0'             Viasystems Group
        byte    "Simtek",0'             Simtek
        byte    "Semicon Devices ",0'             Semicon Devices Singapore           
        byte    "Satron Handelsge",0'             Satron Handelsges           
        byte    "Improv Systems",0'             Improv Systems
        byte    "INDUSYS GmbH",0'             INDUSYS GmbH
        byte    "Corrent",0'             Corrent
        byte    "Infrant Technolo",0'             Infrant Technologies           
        byte    "Ritek Corp",0'             Ritek Corp
        byte    "empowerTel Netwo",0'             empowerTel Networks           
        byte    "Hypertec",0'             Hypertec
        byte    "Cavium Networks",0'             Cavium Networks
        byte    "PLX Technology",0'             PLX Technology
        byte    "Massana Design",0'             Massana Design
        byte    "Intrinsity",0'             Intrinsity
        byte    "Valence Semicond",0'             Valence Semiconductor           
        byte    "Terawave Communi",0'             Terawave Communications           
        byte    "IceFyre Semicond",0'             IceFyre Semiconductor           
        byte    "Primarion",0'             Primarion
        byte    "Picochip Designs",0'             Picochip Designs Ltd           
        byte    "Silverback Syste",0'             Silverback Systems           
        byte    "Jade Star Techno",0'             Jade Star Technologies           
        byte    "Pijnenburg Secur",0'             Pijnenburg Securealink           
        byte    "takeMS - Ultron ",0'             takeMS - Ultron AG           
        byte    "Cambridge Silico",0'             Cambridge Silicon Radio           
        byte    "Swissbit",0'             Swissbit
        byte    "Nazomi Communica",0'             Nazomi Communications           
        byte    "eWave System",0'             eWave System
        byte    "Rockwell Collins",0'             Rockwell Collins
        byte    "Picocel Co Ltd (",0'             Picocel Co Ltd (Paion)           
        byte    "Alphamosaic Ltd",0'             Alphamosaic Ltd
        byte    "Sandburst",0'             Sandburst
        byte    "SiCon Video",0'             SiCon Video
        byte    "NanoAmp Solution",0'             NanoAmp Solutions           
        byte    "Ericsson Technol",0'             Ericsson Technology           
        byte    "PrairieComm",0'             PrairieComm
        byte    "Mitac Internatio",0'             Mitac International           
        byte    "Layer N Networks",0'             Layer N Networks
        byte    "MtekVision (Atsa",0'             MtekVision (Atsana)           
        byte    "Allegro Networks",0'             Allegro Networks
        byte    "Marvell Semicond",0'             Marvell Semiconductors           
        byte    "Netergy Microele",0'             Netergy Microelectronic           
        byte    "NVIDIA",0'             NVIDIA
        byte    "Internet Machine",0'             Internet Machines           
        byte    "Memorysolution G",0'             Memorysolution GmbH           
        byte    "Litchfield Commu",0'             Litchfield Communication           
        byte    "Accton Technolog",0'             Accton Technology           
        byte    "Teradiant Networ",0'             Teradiant Networks           
        byte    "Scaleo Chip",0'             Scaleo Chip
        byte    "Cortina Systems",0'             Cortina Systems
        byte    "RAM Components",0'             RAM Components
        byte    "Raqia Networks",0'             Raqia Networks
        byte    "ClearSpeed",0'             ClearSpeed
        byte    "Matsushita Batte",0'             Matsushita Battery           
        byte    "Xelerated",0'             Xelerated
        byte    "SimpleTech",0'             SimpleTech
        byte    "Utron Technology",0'             Utron Technology
        byte    "Astec Internatio",0'             Astec International           
        byte    "AVM gmbH",0'             AVM gmbH
        byte    "Redux Communicat",0'             Redux Communications           
        byte    "Dot Hill Systems",0'             Dot Hill Systems
        byte    "TeraChip",0'             TeraChip
        byte    "T-RAM Incorporat",0'             T-RAM Incorporated           
        byte    "Innovics Wireles",0'             Innovics Wireless           
        byte    "Teknovus",0'             Teknovus
        byte    "KeyEye Communica",0'             KeyEye Communications           
        byte    "Runcom Technolog",0'             Runcom Technologies           
        byte    "RedSwitch",0'             RedSwitch
        byte    "Dotcast",0'             Dotcast
        byte    "Silicon Mountain",0'             Silicon Mountain Memory           
        byte    "Signia Technolog",0'             Signia Technologies           
        byte    "Pixim",0'             Pixim
        byte    "Galazar Networks",0'             Galazar Networks
        byte    "White Electronic",0'             White Electronic Designs           
        byte    "Patriot Scientif",0'             Patriot Scientific           
        byte    "Neoaxiom Corpora",0'             Neoaxiom Corporation           
        byte    "3Y Power Technol",0'             3Y Power Technology           
        byte    "Scaleo Chip",0'             Scaleo Chip
        byte    "Potentia Power S",0'             Potentia Power Systems           
        byte    "C-guys Incorpora",0'             C-guys Incorporated           
        byte    "Digital Communic",0'             Digital Communications Technology Inc           
        byte    "Silicon-Based Te",0'             Silicon-Based Technology           
        byte    "Fulcrum Microsys",0'             Fulcrum Microsystems           
        byte    "Positivo Informa",0'             Positivo Informatica Ltd           
        byte    "XIOtech Corporat",0'             XIOtech Corporation           
        byte    "PortalPlayer",0'             PortalPlayer
        byte    "Zhiying Software",0'             Zhiying Software
        byte    "ParkerVision Inc",0'             ParkerVision Inc
        byte    "Phonex Broadband",0'             Phonex Broadband
        byte    "Skyworks Solutio",0'             Skyworks Solutions           
        byte    "Entropic Communi",0'             Entropic Communications           
        byte    "I'M Intelligent ",0'             I'M Intelligent Memory Ltd           
        byte    "Zensys A/S",0'             Zensys A/S
        byte    "Legend Silicon C",0'             Legend Silicon Corp           
        byte    "Sci-worx GmbH",0'             Sci-worx GmbH
        byte    "SMSC (Standard M",0'             SMSC (Standard Microsystems)           
        byte    "Renesas Electron",0'             Renesas Electronics           
        byte    "Raza Microelectr",0'             Raza Microelectronics           
        byte    "Phyworks",0'             Phyworks
        byte    "MediaTek",0'             MediaTek
        byte    "Non-cents Produc",0'             Non-cents Productions           
        byte    "US Modular",0'             US Modular
        byte    "Wintegra Ltd",0'             Wintegra Ltd
        byte    "Mathstar",0'             Mathstar
        byte    "StarCore",0'             StarCore
        byte    "Oplus Technologi",0'             Oplus Technologies           
        byte    "Mindspeed",0'             Mindspeed
        byte    "Just Young Compu",0'             Just Young Computer           
        byte    "Radia Communicat",0'             Radia Communications           
        byte    "OCZ",0'             OCZ
        byte    "Emuzed",0'             Emuzed
        byte    "LOGIC Devices",0'             LOGIC Devices
        byte    "Inphi Corporatio",0'             Inphi Corporation           
        byte    "Quake Technologi",0'             Quake Technologies           
        byte    "Vixel",0'             Vixel
        byte    "SolusTek",0'             SolusTek
        byte    "Kongsberg Mariti",0'             Kongsberg Maritime           
        byte    "Faraday Technolo",0'             Faraday Technology           
        byte    "Altium Ltd",0'             Altium Ltd
        byte    "Insyte",0'             Insyte
        byte    "ARM Ltd",0'             ARM Ltd
        byte    "DigiVision",0'             DigiVision
        byte    "Vativ Technologi",0'             Vativ Technologies           
        byte    "Endicott Interco",0'             Endicott Interconnect Technologies           
        byte    "Pericom",0'             Pericom
        byte    "Bandspeed",0'             Bandspeed
        byte    "LeWiz Communicat",0'             LeWiz Communications           
        byte    "CPU Technology",0'             CPU Technology
        byte    "Ramaxel Technolo",0'             Ramaxel Technology           
        byte    "DSP Group",0'             DSP Group
        byte    "Axis Communicati",0'             Axis Communications           
        byte    "Legacy Electroni",0'             Legacy Electronics           
        byte    "Chrontel",0'             Chrontel
        byte    "Powerchip Semico",0'             Powerchip Semiconductor           
        byte    "MobilEye Technol",0'             MobilEye Technologies           
        byte    "Excel Semiconduc",0'             Excel Semiconductor           
        byte    "A-DATA Technolog",0'             A-DATA Technology           
        byte    "VirtualDigm",0'             VirtualDigm
        byte    "G Skill Intl",0'             G Skill Intl
        byte    "Quanta Computer",0'             Quanta Computer
        byte    "Yield Microelect",0'             Yield Microelectronics           
        byte    "Afa Technologies",0'             Afa Technologies
        byte    "KINGBOX Technolo",0'             KINGBOX Technology Co Ltd           
        byte    "Ceva",0'             Ceva
        byte    "iStor Networks",0'             iStor Networks
        byte    "Advance Modules",0'             Advance Modules
        byte    "Microsoft",0'             Microsoft
        byte    "Open-Silicon",0'             Open-Silicon
        byte    "Goal Semiconduct",0'             Goal Semiconductor           
        byte    "ARC Internationa",0'             ARC International           
        byte    "Simmtec",0'             Simmtec
        byte    "Metanoia",0'             Metanoia
        byte    "Key Stream",0'             Key Stream
        byte    "Lowrance Electro",0'             Lowrance Electronics           
        byte    "Adimos",0'             Adimos
        byte    "SiGe Semiconduct",0'             SiGe Semiconductor           
        byte    "Fodus Communicat",0'             Fodus Communications           
        byte    "Credence Systems",0'             Credence Systems Corp           
        byte    "Genesis Microchi",0'             Genesis Microchip Inc           
        byte    "Vihana Inc",0'             Vihana Inc
        byte    "WIS Technologies",0'             WIS Technologies
        byte    "GateChange Techn",0'             GateChange Technologies           
        byte    "High Density Dev",0'             High Density Devices AS           
        byte    "Synopsys",0'             Synopsys
        byte    "Gigaram",0'             Gigaram
        byte    "Enigma Semicondu",0'             Enigma Semiconductor Inc           
        byte    "Century Micro In",0'             Century Micro Inc           
        byte    "Icera Semiconduc",0'             Icera Semiconductor           
        byte    "Mediaworks Integ",0'             Mediaworks Integrated Systems           
        byte    "O'Neil Product D",0'             O'Neil Product Development           
        byte    "Supreme Top Tech",0'             Supreme Top Technology Ltd           
        byte    "MicroDisplay Cor",0'             MicroDisplay Corporation           
        byte    "Team Group Inc",0'             Team Group Inc
        byte    "Sinett Corporati",0'             Sinett Corporation           
        byte    "Toshiba Corporat",0'             Toshiba Corporation           
        byte    "Tensilica",0'             Tensilica
        byte    "SiRF Technology",0'             SiRF Technology
        byte    "Bacoc Inc",0'             Bacoc Inc
        byte    "SMaL Camera Tech",0'             SMaL Camera Technologies           
        byte    "Thomson SC",0'             Thomson SC
        byte    "Airgo Networks",0'             Airgo Networks
        byte    "Wisair Ltd",0'             Wisair Ltd
        byte    "SigmaTel",0'             SigmaTel
        byte    "Arkados",0'             Arkados
        byte    "Compete IT gmbH ",0'             Compete IT gmbH Co KG           
        byte    "Eudar Technology",0'             Eudar Technology Inc           
        byte    "Focus Enhancemen",0'             Focus Enhancements           
        byte    "Xyratex",0'             Xyratex
        byte    "Specular Network",0'             Specular Networks           
        byte    "Patriot Memory (",0'             Patriot Memory (PDP Systems)           
        byte    "U-Chip Technolog",0'             U-Chip Technology Corp           
        byte    "Silicon Optix",0'             Silicon Optix
        byte    "Greenfield Netwo",0'             Greenfield Networks           
        byte    "CompuRAM GmbH",0'             CompuRAM GmbH
        byte    "Stargen Inc",0'             Stargen Inc
        byte    "NetCell Corporat",0'             NetCell Corporation           
        byte    "Excalibrus Techn",0'             Excalibrus Technologies Ltd           
        byte    "SCM Microsystems",0'             SCM Microsystems
        byte    "Xsigo Systems In",0'             Xsigo Systems Inc           
        byte    "CHIPS & Systems ",0'             CHIPS & Systems Inc           
        byte    "Tier 1 Multichip",0'             Tier 1 Multichip Solutions           
        byte    "CWRL Labs",0'             CWRL Labs
        byte    "Teradici",0'             Teradici
        byte    "Gigaram Inc",0'             Gigaram Inc
        byte    "g2 Microsystems",0'             g2 Microsystems
        byte    "PowerFlash Semic",0'             PowerFlash Semiconductor           
        byte    "P.A. Semi Inc",0'             P.A. Semi Inc
        byte    "NovaTech Solutio",0'             NovaTech Solutions S.A.           
        byte    "c2 Microsystems ",0'             c2 Microsystems Inc           
        byte    "Level5 Networks",0'             Level5 Networks
        byte    "COS Memory AG",0'             COS Memory AG
        byte    "Innovasic Semico",0'             Innovasic Semiconductor           
        byte    "02IC Co Ltd",0'             02IC Co Ltd
        byte    "Tabula Inc",0'             Tabula Inc
        byte    "Crucial Technolo",0'             Crucial Technology           
        byte    "Chelsio Communic",0'             Chelsio Communications           
        byte    "Solarflare Commu",0'             Solarflare Communications           
        byte    "Xambala Inc",0'             Xambala Inc
        byte    "EADS Astrium",0'             EADS Astrium
        byte    "Terra Semiconduc",0'             Terra Semiconductor Inc           
        byte    "Imaging Works In",0'             Imaging Works Inc           
        byte    "Astute Networks ",0'             Astute Networks Inc           
        byte    "Tzero",0'             Tzero
        byte    "Emulex",0'             Emulex
        byte    "Power-One",0'             Power-One
        byte    "Pulse~LINK Inc",0'             Pulse~LINK Inc
        byte    "Hon Hai Precisio",0'             Hon Hai Precision Industry           
        byte    "White Rock Netwo",0'             White Rock Networks Inc           
        byte    "Telegent Systems",0'             Telegent Systems USA Inc           
        byte    "Atrua Technologi",0'             Atrua Technologies Inc           
        byte    "Acbel Polytech I",0'             Acbel Polytech Inc           
        byte    "eRide Inc",0'             eRide Inc
        byte    "ULi Electronics ",0'             ULi Electronics Inc           
        byte    "Magnum Semicondu",0'             Magnum Semiconductor Inc           
        byte    "neoOne Technolog",0'             neoOne Technology Inc           
        byte    "Connex Technolog",0'             Connex Technology Inc           
        byte    "Stream Processor",0'             Stream Processors Inc           
        byte    "Focus Enhancemen",0'             Focus Enhancements           
        byte    "Telecis Wireless",0'             Telecis Wireless Inc           
        byte    "uNav Microelectr",0'             uNav Microelectronics           
        byte    "Tarari Inc",0'             Tarari Inc
        byte    "Ambric Inc",0'             Ambric Inc
        byte    "Newport Media In",0'             Newport Media Inc           
        byte    "VMTS",0'             VMTS
        byte    "Enuclia Semicond",0'             Enuclia Semiconductor Inc           
        byte    "Virtium Technolo",0'             Virtium Technology Inc           
        byte    "Solid State Syst",0'             Solid State System Co Ltd           
        byte    "Kian Tech LLC",0'             Kian Tech LLC
        byte    "Artimi",0'             Artimi
        byte    "Power Quotient I",0'             Power Quotient International           
        byte    "Avago Technologi",0'             Avago Technologies           
        byte    "ADTechnology",0'             ADTechnology
        byte    "Sigma Designs",0'             Sigma Designs
        byte    "SiCortex Inc",0'             SiCortex Inc
        byte    "Ventura Technolo",0'             Ventura Technology Group           
        byte    "eASIC",0'             eASIC
        byte    "M.H.S. SAS",0'             M.H.S. SAS
        byte    "Micro Star Inter",0'             Micro Star International           
        byte    "Rapport Inc",0'             Rapport Inc
        byte    "Makway Internati",0'             Makway International           
        byte    "Broad Reach Engi",0'             Broad Reach Engineering Co           
        byte    "Semiconductor Mf",0'             Semiconductor Mfg Intl Corp           
        byte    "SiConnect",0'             SiConnect
        byte    "FCI USA Inc",0'             FCI USA Inc
        byte    "Validity Sensors",0'             Validity Sensors
        byte    "Coney Technology",0'             Coney Technology Co Ltd           
        byte    "Spans Logic",0'             Spans Logic
        byte    "Neterion Inc",0'             Neterion Inc
        byte    "Qimonda",0'             Qimonda
        byte    "New Japan Radio ",0'             New Japan Radio Co Ltd           
        byte    "Velogix",0'             Velogix
        byte    "Montalvo Systems",0'             Montalvo Systems
        byte    "iVivity Inc",0'             iVivity Inc
        byte    "Walton Chaintech",0'             Walton Chaintech
        byte    "AENEON",0'             AENEON
        byte    "Lorom Industrial",0'             Lorom Industrial Co Ltd           
        byte    "Radiospire Netwo",0'             Radiospire Networks           
        byte    "Sensio Technolog",0'             Sensio Technologies Inc           
        byte    "Nethra Imaging",0'             Nethra Imaging
        byte    "Hexon Technology",0'             Hexon Technology Pte Ltd           
        byte    "CompuStocx (CSX)",0'             CompuStocx (CSX)
        byte    "Methode Electron",0'             Methode Electronics Inc           
        byte    "Connect One Ltd",0'             Connect One Ltd
        byte    "Opulan Technolog",0'             Opulan Technologies           
        byte    "Septentrio NV",0'             Septentrio NV
        byte    "Goldenmars Techn",0'             Goldenmars Technology Inc           
        byte    "Kreton Corporati",0'             Kreton Corporation           
        byte    "Cochlear Ltd",0'             Cochlear Ltd
        byte    "Altair Semicondu",0'             Altair Semiconductor           
        byte    "NetEffect Inc",0'             NetEffect Inc
        byte    "Spansion Inc",0'             Spansion Inc
        byte    "Taiwan Semicondu",0'             Taiwan Semiconductor Mfg           
        byte    "Emphany Systems ",0'             Emphany Systems Inc           
        byte    "ApaceWave Techno",0'             ApaceWave Technologies           
        byte    "Mobilygen Corpor",0'             Mobilygen Corporation           
        byte    "Tego",0'             Tego
        byte    "Cswitch Corporat",0'             Cswitch Corporation           
        byte    "Haier (Beijing) ",0'             Haier (Beijing) IC Design Co           
        byte    "MetaRAM",0'             MetaRAM
        byte    "Axel Electronics",0'             Axel Electronics Co Ltd           
        byte    "Tilera Corporati",0'             Tilera Corporation           
        byte    "Aquantia",0'             Aquantia
        byte    "Vivace Semicondu",0'             Vivace Semiconductor           
        byte    "Redpine Signals",0'             Redpine Signals
        byte    "Octalica",0'             Octalica
        byte    "InterDigital Com",0'             InterDigital Communications           
        byte    "Avant Technology",0'             Avant Technology
        byte    "Asrock Inc",0'             Asrock Inc
        byte    "Availink",0'             Availink
        byte    "Quartics Inc",0'             Quartics Inc
        byte    "Element CXI",0'             Element CXI
        byte    "Innovaciones Mic",0'             Innovaciones Microelectronicas           
        byte    "VeriSilicon Micr",0'             VeriSilicon Microelectronics           
        byte    "W5 Networks",0'             W5 Networks
        byte    "MOVEKING",0'             MOVEKING
        byte    "Mavrix Technolog",0'             Mavrix Technology Inc           
        byte    "CellGuide Ltd",0'             CellGuide Ltd
        byte    "Faraday Technolo",0'             Faraday Technology           
        byte    "Diablo Technolog",0'             Diablo Technologies Inc           
        byte    "Jennic",0'             Jennic
        byte    "Octasic",0'             Octasic
        byte    "Molex Incorporat",0'             Molex Incorporated           
        byte    "3Leaf Networks",0'             3Leaf Networks
        byte    "Bright Micron Te",0'             Bright Micron Technology           
        byte    "Netxen",0'             Netxen
        byte    "NextWave Broadba",0'             NextWave Broadband Inc           
        byte    "DisplayLink",0'             DisplayLink
        byte    "ZMOS Technology",0'             ZMOS Technology
        byte    "Tec-Hill",0'             Tec-Hill
        byte    "Multigig Inc",0'             Multigig Inc
        byte    "Amimon",0'             Amimon
        byte    "Euphonic Technol",0'             Euphonic Technologies Inc           
        byte    "BRN Phoenix",0'             BRN Phoenix
        byte    "InSilica",0'             InSilica
        byte    "Ember Corporatio",0'             Ember Corporation           
        byte    "Avexir Technolog",0'             Avexir Technologies Corporation           
        byte    "Echelon Corporat",0'             Echelon Corporation           
        byte    "Edgewater Comput",0'             Edgewater Computer Systems           
        byte    "XMOS Semiconduct",0'             XMOS Semiconductor Ltd           
        byte    "GENUSION Inc",0'             GENUSION Inc
        byte    "Memory Corp NV",0'             Memory Corp NV
        byte    "SiliconBlue Tech",0'             SiliconBlue Technologies           
        byte    "Rambus Inc",0'             Rambus Inc
        byte    "Andes Technology",0'             Andes Technology Corporation           
        byte    "Coronis Systems",0'             Coronis Systems
        byte    "Achronix Semicon",0'             Achronix Semiconductor           
        byte    "Siano Mobile Sil",0'             Siano Mobile Silicon Ltd           
        byte    "Semtech Corporat",0'             Semtech Corporation           
        byte    "Pixelworks Inc",0'             Pixelworks Inc
        byte    "Gaisler Research",0'             Gaisler Research AB           
        byte    "Teranetics",0'             Teranetics
        byte    "Toppan Printing ",0'             Toppan Printing Co Ltd           
        byte    "Kingxcon",0'             Kingxcon
        byte    "Silicon Integrat",0'             Silicon Integrated Systems           
        byte    "I-O Data Device ",0'             I-O Data Device Inc           
        byte    "NDS Americas Inc",0'             NDS Americas Inc
        byte    "Solomon Systech ",0'             Solomon Systech Limited           
        byte    "On Demand Microe",0'             On Demand Microelectronics           
        byte    "Amicus Wireless ",0'             Amicus Wireless Inc           
        byte    "SMARDTV SNC",0'             SMARDTV SNC
        byte    "Comsys Communica",0'             Comsys Communication Ltd           
        byte    "Movidia Ltd",0'             Movidia Ltd
        byte    "Javad GNSS Inc",0'             Javad GNSS Inc
        byte    "Montage Technolo",0'             Montage Technology Group           
        byte    "Trident Microsys",0'             Trident Microsystems           
        byte    "Super Talent",0'             Super Talent
        byte    "Optichron Inc",0'             Optichron Inc
        byte    "Future Waves UK ",0'             Future Waves UK Ltd           
        byte    "SiBEAM Inc",0'             SiBEAM Inc
        byte    "InicoreInc",0'             InicoreInc
        byte    "Virident Systems",0'             Virident Systems
        byte    "M2000 Inc",0'             M2000 Inc
        byte    "ZeroG Wireless I",0'             ZeroG Wireless Inc           
        byte    "Gingle Technolog",0'             Gingle Technology Co Ltd           
        byte    "Space Micro Inc",0'             Space Micro Inc
        byte    "Wilocity",0'             Wilocity
        byte    "Novafora Inc",0'             Novafora Inc
        byte    "iKoa Corporation",0'             iKoa Corporation
        byte    "ASint Technology",0'             ASint Technology
        byte    "Ramtron",0'             Ramtron
        byte    "Plato Networks I",0'             Plato Networks Inc           
        byte    "IPtronics AS",0'             IPtronics AS
        byte    "Infinite-Memorie",0'             Infinite-Memories           
        byte    "Parade Technolog",0'             Parade Technologies Inc           
        byte    "Dune Networks",0'             Dune Networks
        byte    "GigaDevice Semic",0'             GigaDevice Semiconductor           
        byte    "Modu Ltd",0'             Modu Ltd
        byte    "CEITEC",0'             CEITEC
        byte    "Northrop Grumman",0'             Northrop Grumman
        byte    "XRONET Corporati",0'             XRONET Corporation           
        byte    "Sicon Semiconduc",0'             Sicon Semiconductor AB           
        byte    "Atla Electronics",0'             Atla Electronics Co Ltd           
        byte    "TOPRAM Technolog",0'             TOPRAM Technology           
        byte    "Silego Technolog",0'             Silego Technology Inc           
        byte    "Kinglife",0'             Kinglife
        byte    "Ability Industri",0'             Ability Industries Ltd           
        byte    "Silicon Power Co",0'             Silicon Power Computer & Communications           
        byte    "Augusta Technolo",0'             Augusta Technology Inc           
        byte    "Nantronics Semic",0'             Nantronics Semiconductors           
        byte    "Hilscher Gesells",0'             Hilscher Gesellschaft           
        byte    "Quixant Ltd",0'             Quixant Ltd
        byte    "Percello Ltd",0'             Percello Ltd
        byte    "NextIO Inc",0'             NextIO Inc
        byte    "Scanimetrics Inc",0'             Scanimetrics Inc
        byte    "FS-Semi Company ",0'             FS-Semi Company Ltd           
        byte    "Infinera Corpora",0'             Infinera Corporation           
        byte    "SandForce Inc",0'             SandForce Inc
        byte    "Lexar Media",0'             Lexar Media
        byte    "Teradyne Inc",0'             Teradyne Inc
        byte    "Memory Exchange ",0'             Memory Exchange Corp           
        byte    "Suzhou Smartek E",0'             Suzhou Smartek Electronics           
        byte    "Avantium Corpora",0'             Avantium Corporation           
        byte    "ATP Electronics ",0'             ATP Electronics Inc           
        byte    "Valens Semicondu",0'             Valens Semiconductor Ltd           
        byte    "Agate Logic Inc",0'             Agate Logic Inc
        byte    "Netronome",0'             Netronome
        byte    "Zenverge Inc",0'             Zenverge Inc
        byte    "N-trig Ltd",0'             N-trig Ltd
        byte    "SanMax Technolog",0'             SanMax Technologies Inc           
        byte    "Contour Semicond",0'             Contour Semiconductor Inc           
        byte    "TwinMOS",0'             TwinMOS
        byte    "Silicon Systems ",0'             Silicon Systems Inc           
        byte    "V-Color Technolo",0'             V-Color Technology Inc           
        byte    "Certicom Corpora",0'             Certicom Corporation           
        byte    "JSC ICC Milandr",0'             JSC ICC Milandr
        byte    "PhotoFast Global",0'             PhotoFast Global Inc           
        byte    "InnoDisk Corpora",0'             InnoDisk Corporation           
        byte    "Muscle Power",0'             Muscle Power
        byte    "Energy Micro",0'             Energy Micro
        byte    "Innofidei",0'             Innofidei
        byte    "CopperGate Commu",0'             CopperGate Communications           
        byte    "Holtek Semicondu",0'             Holtek Semiconductor Inc           
        byte    "Myson Century In",0'             Myson Century Inc           
        byte    "FIDELIX",0'             FIDELIX
        byte    "Red Digital Cine",0'             Red Digital Cinema           
        byte    "Densbits Technol",0'             Densbits Technology           
        byte    "Zempro",0'             Zempro
        byte    "MoSys",0'             MoSys
        byte    "Provigent",0'             Provigent
        byte    "Triad Semiconduc",0'             Triad Semiconductor Inc           
        byte    "Siklu Communicat",0'             Siklu Communication Ltd           
        byte    "A Force Manufact",0'             A Force Manufacturing Ltd           
        byte    "Strontium",0'             Strontium
        byte    "ALi Corp (Abilis",0'             ALi Corp (Abilis Systems)           
        byte    "Siglead Inc",0'             Siglead Inc
        byte    "Ubicom Inc",0'             Ubicom Inc
        byte    "Unifosa Corporat",0'             Unifosa Corporation           
        byte    "Stretch Inc",0'             Stretch Inc
        byte    "Lantiq Deutschla",0'             Lantiq Deutschland GmbH           
        byte    "Visipro.",0'             Visipro.
        byte    "EKMemory",0'             EKMemory
        byte    "Microelectronics",0'             Microelectronics Institute ZTE           
        byte    "u-blox AG",0'             u-blox AG
        byte    "Carry Technology",0'             Carry Technology Co Ltd           
        byte    "Nokia",0'             Nokia
        byte    "King Tiger Techn",0'             King Tiger Technology           
        byte    "Sierra Wireless",0'             Sierra Wireless
        byte    "HT Micron",0'             HT Micron
        byte    "Albatron Technol",0'             Albatron Technology Co Ltd           
        byte    "Leica Geosystems",0'             Leica Geosystems AG           
        byte    "BroadLight",0'             BroadLight
        byte    "AEXEA",0'             AEXEA
        byte    "ClariPhy Communi",0'             ClariPhy Communications Inc           
        byte    "Green Plug",0'             Green Plug
        byte    "Design Art Netwo",0'             Design Art Networks           
        byte    "Mach Xtreme Tech",0'             Mach Xtreme Technology Ltd           
        byte    "ATO Solutions Co",0'             ATO Solutions Co Ltd           
        byte    "Ramsta",0'             Ramsta
        byte    "Greenliant Syste",0'             Greenliant Systems Ltd           
        byte    "Teikon",0'             Teikon
        byte    "Antec Hadron",0'             Antec Hadron
        byte    "NavCom Technolog",0'             NavCom Technology Inc           
        byte    "Shanghai Fudan M",0'             Shanghai Fudan Microelectronics           
        byte    "Calxeda Inc",0'             Calxeda Inc
        byte    "JSC EDC Electron",0'             JSC EDC Electronics           
        byte    "Kandit Technolog",0'             Kandit Technology Co Ltd           
        byte    "Ramos Technology",0'             Ramos Technology
        byte    "Goldenmars Techn",0'             Goldenmars Technology           
        byte    "XeL Technology I",0'             XeL Technology Inc           
        byte    "Newzone Corporat",0'             Newzone Corporation           
        byte    "ShenZhen MercyPo",0'             ShenZhen MercyPower Tech           
        byte    "Nanjing Yihuo Te",0'             Nanjing Yihuo Technology           
        byte    "Nethra Imaging I",0'             Nethra Imaging Inc           
        byte    "SiTel Semiconduc",0'             SiTel Semiconductor BV           
        byte    "SolidGear Corpor",0'             SolidGear Corporation           
        byte    "Topower Computer",0'             Topower Computer Ind Co Ltd           
        byte    "Wilocity",0'             Wilocity
        byte    "Profichip GmbH",0'             Profichip GmbH
        byte    "Gerad Technologi",0'             Gerad Technologies           
        byte    "Ritek Corporatio",0'             Ritek Corporation           
        byte    "Gomos Technology",0'             Gomos Technology Limited           
        byte    "Memoright Corpor",0'             Memoright Corporation           
        byte    "D-Broad Inc",0'             D-Broad Inc
        byte    "HiSilicon Techno",0'             HiSilicon Technologies           
        byte    "Syndiant Inc.",0'             Syndiant Inc.
        byte    "Enverv Inc",0'             Enverv Inc
        byte    "Cognex",0'             Cognex
        byte    "Xinnova Technolo",0'             Xinnova Technology Inc           
        byte    "Ultron AG",0'             Ultron AG
        byte    "Concord Idea Cor",0'             Concord Idea Corporation           
        byte    "AIM Corporation",0'             AIM Corporation
        byte    "Lifetime Memory ",0'             Lifetime Memory Products           
        byte    "Ramsway",0'             Ramsway
        byte    "Recore Systems B",0'             Recore Systems B.V.           
        byte    "Haotian Jinshibo",0'             Haotian Jinshibo Science Tech           
        byte    "Being Advanced M",0'             Being Advanced Memory           
        byte    "Adesto Technolog",0'             Adesto Technologies           
        byte    "Giantec Semicond",0'             Giantec Semiconductor Inc           
        byte    "HMD Electronics ",0'             HMD Electronics AG           
        byte    "Gloway Internati",0'             Gloway International (HK)           
        byte    "Kingcore",0'             Kingcore
        byte    "Anucell Technolo",0'             Anucell Technology Holding           
        byte    "Accord Software ",0'             Accord Software & Systems Pvt. Ltd           
        byte    "Active-Semi Inc",0'             Active-Semi Inc
        byte    "Denso Corporatio",0'             Denso Corporation           
        byte    "TLSI Inc",0'             TLSI Inc
        byte    "Qidan",0'             Qidan
        byte    "Mustang",0'             Mustang
        byte    "Orca Systems",0'             Orca Systems
        byte    "Passif Semicondu",0'             Passif Semiconductor           
        byte    "GigaDevice Semic",0'             GigaDevice Semiconductor (Beijing)           
        byte    "Memphis Electron",0'             Memphis Electronic           
        byte    "Beckhoff Automat",0'             Beckhoff Automation GmbH           
        byte    "Harmony Semicond",0'             Harmony Semiconductor Corp           
        byte    "Air Computers SR",0'             Air Computers SRL           
        byte    "TMT Memory",0'             TMT Memory
        byte    "Eorex Corporatio",0'             Eorex Corporation           
        byte    "Xingtera",0'             Xingtera
        byte    "Netsol",0'             Netsol
        byte    "Bestdon Technolo",0'             Bestdon Technology Co Ltd           
        byte    "Baysand Inc",0'             Baysand Inc
        byte    "Uroad Technology",0'             Uroad Technology Co Ltd           
        byte    "Wilk Elektronik ",0'             Wilk Elektronik S.A.           
        byte    "AAI",0'             AAI
        byte    "Harman",0'             Harman
        byte    "Berg Microelectr",0'             Berg Microelectronics Inc           
        byte    "ASSIA Inc",0'             ASSIA Inc
        byte    "Visiontek Produc",0'             Visiontek Products LLC           
        byte    "OCMEMORY",0'             OCMEMORY
        byte    "Welink Solution ",0'             Welink Solution Inc           
        byte    "Shark Gaming",0'             Shark Gaming
        byte    "Avalanche Techno",0'             Avalanche Technology           
        byte    "R&D Center ELVEE",0'             R&D Center ELVEES OJSC           
        byte    "KingboMars Techn",0'             KingboMars Technology Co Ltd           
        byte    "High Bridge Solu",0'             High Bridge Solutions Industria Eletronica           
        byte    "Transcend Techno",0'             Transcend Technology Co Ltd           
        byte    "Everspin Technol",0'             Everspin Technologies           
        byte    "Hon-Hai Precisio",0'             Hon-Hai Precision           
        byte    "Smart Storage Sy",0'             Smart Storage Systems           
        byte    "Toumaz Group",0'             Toumaz Group
        byte    "Zentel Electroni",0'             Zentel Electronics Corporation           
        byte    "Panram Internati",0'             Panram International Corporation           
        byte    "Silicon Space Te",0'             Silicon Space Technology           
        byte    "LITE-ON IT Corpo",0'             LITE-ON IT Corporation           
        byte    "Inuitive",0'             Inuitive
        byte    "HMicro",0'             HMicro
        byte    "BittWare Inc",0'             BittWare Inc
        byte    "GLOBALFOUNDRIES",0'             GLOBALFOUNDRIES
        byte    "ACPI Digital Co ",0'             ACPI Digital Co Ltd           
        byte    "Annapurna Labs",0'             Annapurna Labs
        byte    "AcSiP Technology",0'             AcSiP Technology Corporation           
        byte    "Idea! Electronic",0'             Idea! Electronic Systems           
        byte    "Gowe Technology ",0'             Gowe Technology Co Ltd           
        byte    "Hermes Testing S",0'             Hermes Testing Solutions Inc           
        byte    "Positivo BGH",0'             Positivo BGH
        byte    "Intelligence Sil",0'             Intelligence Silicon Technology           
        byte    "3D PLUS",0'             3D PLUS
        byte    "Diehl Aerospace",0'             Diehl Aerospace
        byte    "Fairchild",0'             Fairchild
        byte    "Mercury Systems",0'             Mercury Systems
        byte    "Sonics Inc",0'             Sonics Inc
        byte    "Emerson Automati",0'             Emerson Automation Solutions           
        byte    "Shenzhen Jinge I",0'             Shenzhen Jinge Information Co Ltd           
        byte    "SCWW",0'             SCWW
        byte    "Silicon Motion I",0'             Silicon Motion Inc           
        byte    "Anurag",0'             Anurag
        byte    "King Kong",0'             King Kong
        byte    "FROM30 Co Ltd",0'             FROM30 Co Ltd
        byte    "Gowin Semiconduc",0'             Gowin Semiconductor Corp           
        byte    "Fremont Micro De",0'             Fremont Micro Devices Ltd           
        byte    "Ericsson Modems",0'             Ericsson Modems
        byte    "Exelis",0'             Exelis
        byte    "Satixfy Ltd",0'             Satixfy Ltd
        byte    "Galaxy Microsyst",0'             Galaxy Microsystems Ltd           
        byte    "Gloway Internati",0'             Gloway International Co Ltd           
        byte    "Lab",0'             Lab
        byte    "Smart Energy Ins",0'             Smart Energy Instruments           
        byte    "Approved Memory ",0'             Approved Memory Corporation           
        byte    "Axell Corporatio",0'             Axell Corporation           
        byte    "Essencore Limite",0'             Essencore Limited           
        byte    "Phytium",0'             Phytium
        byte    "UniIC Semiconduc",0'             UniIC Semiconductors Co Ltd           
        byte    "Ambiq Micro",0'             Ambiq Micro
        byte    "eveRAM Technolog",0'             eveRAM Technology Inc           
        byte    "Infomax",0'             Infomax
        byte    "Butterfly Networ",0'             Butterfly Network Inc           
        byte    "Shenzhen City Gc",0'             Shenzhen City Gcai Electronics           
        byte    "Stack Devices Co",0'             Stack Devices Corporation           
        byte    "ADK Media Group",0'             ADK Media Group
        byte    "TSP Global Co Lt",0'             TSP Global Co Ltd           
        byte    "HighX",0'             HighX
        byte    "Shenzhen Elicks ",0'             Shenzhen Elicks Technology           
        byte    "XinKai/Silicon K",0'             XinKai/Silicon Kaiser           
        byte    "Google Inc",0'             Google Inc
        byte    "Dasima Internati",0'             Dasima International Development           
        byte    "Leahkinn Technol",0'             Leahkinn Technology Limited           
        byte    "HIMA Paul Hildeb",0'             HIMA Paul Hildebrandt GmbH Co KG           
        byte    "Keysight Technol",0'             Keysight Technologies           
        byte    "Techcomp Interna",0'             Techcomp International (Fastable)           
        byte    "Ancore Technolog",0'             Ancore Technology Corporation           
        byte    "Nuvoton",0'             Nuvoton
        byte    "Korea Uhbele Int",0'             Korea Uhbele International Group Ltd           
        byte    "Ikegami Tsushink",0'             Ikegami Tsushinki Co Ltd           
        byte    "RelChip Inc",0'             RelChip Inc
        byte    "Baikal Electroni",0'             Baikal Electronics           
        byte    "Nemostech Inc",0'             Nemostech Inc
        byte    "Memorysolution G",0'             Memorysolution GmbH           
        byte    "Silicon Integrat",0'             Silicon Integrated Systems Corporation           
        byte    "Xiede",0'             Xiede
        byte    "BRC",0'             BRC
        byte    "Flash Chi",0'             Flash Chi
        byte    "Jone",0'             Jone
        byte    "GCT Semiconducto",0'             GCT Semiconductor Inc           
        byte    "Hong Kong Zetta ",0'             Hong Kong Zetta Device Technology           
        byte    "Unimemory Techno",0'             Unimemory Technology(s) Pte Ltd           
        byte    "Cuso",0'             Cuso
        byte    "Kuso",0'             Kuso
        byte    "Uniquify Inc",0'             Uniquify Inc
        byte    "Skymedi Corporat",0'             Skymedi Corporation           
        byte    "Core Chance Co L",0'             Core Chance Co Ltd           
        byte    "Tekism Co Ltd",0'             Tekism Co Ltd
        byte    "Seagate Technolo",0'             Seagate Technology PLC           
        byte    "Hong Kong Gaia G",0'             Hong Kong Gaia Group Co Limited           
        byte    "Gigacom Semicond",0'             Gigacom Semiconductor LLC           
        byte    "V2 Technologies",0'             V2 Technologies
        byte    "TLi",0'             TLi
        byte    "Neotion",0'             Neotion
        byte    "Lenovo",0'             Lenovo
        byte    "Shenzhen Zhongte",0'             Shenzhen Zhongteng Electronic Corp Ltd           
        byte    "Compound Photoni",0'             Compound Photonics           
        byte    "in2H2 inc",0'             in2H2 inc
        byte    "Shenzhen Pango M",0'             Shenzhen Pango Microsystems Co Ltd           
        byte    "Vasekey",0'             Vasekey
        byte    "Cal-Comp Industr",0'             Cal-Comp Industria de Semicondutores           
        byte    "Eyenix Co Ltd",0'             Eyenix Co Ltd
        byte    "Heoriady",0'             Heoriady
        byte    "Accelerated Memo",0'             Accelerated Memory Production Inc           
        byte    "INVECAS Inc",0'             INVECAS Inc
        byte    "AP Memory",0'             AP Memory
        byte    "Douqi Technology",0'             Douqi Technology
        byte    "Etron Technology",0'             Etron Technology Inc           
        byte    "Indie Semiconduc",0'             Indie Semiconductor           
        byte    "Socionext Inc",0'             Socionext Inc
        byte    "HGST",0'             HGST
        byte    "EVGA",0'             EVGA
        byte    "Audience Inc",0'             Audience Inc
        byte    "EpicGear",0'             EpicGear
        byte    "Vitesse Enterpri",0'             Vitesse Enterprise Co           
        byte    "Foxtronn Interna",0'             Foxtronn International Corporation           
        byte    "Bretelon Inc",0'             Bretelon Inc
        byte    "Graphcore",0'             Graphcore
        byte    "Eoplex Inc",0'             Eoplex Inc
        byte    "MaxLinear Inc",0'             MaxLinear Inc
        byte    "ETA Devices",0'             ETA Devices
        byte    "LOKI",0'             LOKI
        byte    "IMS Electronics ",0'             IMS Electronics Co Ltd           
        byte    "Dosilicon Co Ltd",0'             Dosilicon Co Ltd
        byte    "Dolphin Integrat",0'             Dolphin Integration           
        byte    "Shenzhen Mic Ele",0'             Shenzhen Mic Electronics Technolog           
        byte    "Boya Microelectr",0'             Boya Microelectronics Inc           
        byte    "Geniachip (Roche",0'             Geniachip (Roche)           
        byte    "Axign",0'             Axign
        byte    "Kingred Electron",0'             Kingred Electronic Technology Ltd           
        byte    "Chao Yue Zhuo Co",0'             Chao Yue Zhuo Computer Business Dept.           
        byte    "Guangzhou Si Nuo",0'             Guangzhou Si Nuo Electronic Technology.           
        byte    "Crocus Technolog",0'             Crocus Technology Inc           
        byte    "Creative Chips G",0'             Creative Chips GmbH           
        byte    "GE Aviation Syst",0'             GE Aviation Systems LLC.           
        byte    "Asgard",0'             Asgard
        byte    "Good Wealth Tech",0'             Good Wealth Technology Ltd           
        byte    "TriCor Technolog",0'             TriCor Technologies           
        byte    "Nova-Systems Gmb",0'             Nova-Systems GmbH           
        byte    "JUHOR",0'             JUHOR
        byte    "Zhuhai Douke Com",0'             Zhuhai Douke Commerce Co Ltd           
        byte    "DSL Memory",0'             DSL Memory
        byte    "Anvo-Systems Dre",0'             Anvo-Systems Dresden GmbH           
        byte    "Realtek",0'             Realtek
        byte    "AltoBeam",0'             AltoBeam
        byte    "Wave Computing",0'             Wave Computing
        byte    "Beijing TrustNet",0'             Beijing TrustNet Technology Co Ltd           
        byte    "Innovium Inc",0'             Innovium Inc
        byte    "Starsway Technol",0'             Starsway Technology Limited           
        byte    "Weltronics Co LT",0'             Weltronics Co LTD           
        byte    "VMware Inc",0'             VMware Inc
        byte    "Hewlett Packard ",0'             Hewlett Packard Enterprise           
        byte    "INTENSO",0'             INTENSO
        byte    "Puya Semiconduct",0'             Puya Semiconductor           
        byte    "MEMORFI",0'             MEMORFI
        byte    "MSC Technologies",0'             MSC Technologies GmbH           
        byte    "Txrui",0'             Txrui
        byte    "SiFive Inc",0'             SiFive Inc
        byte    "Spreadtrum Commu",0'             Spreadtrum Communications           
        byte    "XTX Technology L",0'             XTX Technology Limited           
        byte    "UMAX Technology",0'             UMAX Technology
        byte    "Shenzhen Yong Sh",0'             Shenzhen Yong Sheng Technology           
        byte    "SNOAMOO (Shenzhe",0'             SNOAMOO (Shenzhen Kai Zhuo Yue)           
        byte    "Daten Tecnologia",0'             Daten Tecnologia LTDA           
        byte    "Shenzhen XinRuiY",0'             Shenzhen XinRuiYan Electronics           
        byte    "Eta Compute",0'             Eta Compute
        byte    "Energous",0'             Energous
        byte    "Raspberry Pi Tra",0'             Raspberry Pi Trading Ltd           
        byte    "Shenzhen Chixing",0'             Shenzhen Chixingzhe Tech Co Ltd           
        byte    "Silicon Mobility",0'             Silicon Mobility
        byte    "IQ-Analog Corpor",0'             IQ-Analog Corporation           
        byte    "Uhnder Inc",0'             Uhnder Inc
        byte    "Impinj",0'             Impinj
        byte    "DEPO Computers",0'             DEPO Computers
        byte    "Nespeed Sysems",0'             Nespeed Sysems
        byte    "Yangtze Memory T",0'             Yangtze Memory Technologies Co Ltd           
        byte    "MemxPro Inc",0'             MemxPro Inc
        byte    "Tammuz Co Ltd",0'             Tammuz Co Ltd
        byte    "Allwinner Techno",0'             Allwinner Technology           
        byte    "Shenzhen City Fu",0'             Shenzhen City Futian District Qing Xuan Tong Computer Trading Firm           
        byte    "XMC",0'             XMC
        byte    "Teclast",0'             Teclast
        byte    "Maxsun",0'             Maxsun
        byte    "Haiguang Integra",0'             Haiguang Integrated Circuit Design           
        byte    "RamCENTER Techno",0'             RamCENTER Technology           
        byte    "Phison Electroni",0'             Phison Electronics Corporation           
        byte    "Guizhou Huaxinto",0'             Guizhou Huaxintong Semi-Conductor           
        byte    "Network Intellig",0'             Network Intelligence           
        byte    "Continental Tech",0'             Continental Technology (Holdings)           
        byte    "Guangzhou Huayan",0'             Guangzhou Huayan Suning Electronic           
        byte    "Guangzhou Zhouji",0'             Guangzhou Zhouji Electronic Co Ltd           
        byte    "Shenzhen Giant H",0'             Shenzhen Giant Hui Kang Tech Co Ltd           
        byte    "Shenzhen Yilong ",0'             Shenzhen Yilong Innovative Co Ltd           
        byte    "Neo Forza",0'             Neo Forza
        byte    "Lyontek Inc",0'             Lyontek Inc
        byte    "Shanghai Kuxin M",0'             Shanghai Kuxin Microelectronics Ltd           
        byte    "Shenzhen Larix T",0'             Shenzhen Larix Technology Co Ltd           
        byte    "Qbit Semiconduct",0'             Qbit Semiconductor Ltd           
        byte    "Insignis Technol",0'             Insignis Technology Corporation           
        byte    "Lanson Memory Co",0'             Lanson Memory Co Ltd           
        byte    "Shenzhen Superwa",0'             Shenzhen Superway Electronics Co Ltd           
        byte    "Canaan-Creative ",0'             Canaan-Creative Co Ltd           
        byte    "Black Diamond Me",0'             Black Diamond Memory           
        byte    "Shenzhen City Pa",0'             Shenzhen City Parker Baking Electronics           
        byte    "Shenzhen Baihong",0'             Shenzhen Baihong Technology Co Ltd           
        byte    "GEO Semiconducto",0'             GEO Semiconductors           
        byte    "OCPC",0'             OCPC
        byte    "Artery Technolog",0'             Artery Technology Co Ltd           
        byte    "Jinyu",0'             Jinyu
        byte    "ShenzhenYing Chi",0'             ShenzhenYing Chi Technology Development           
        byte    "Shenzhen Pengche",0'             Shenzhen Pengcheng Xin Technology           
        byte    "Pegasus Semicond",0'             Pegasus Semiconductor (Shanghai) Co           
        byte    "Mythic Inc",0'             Mythic Inc
        byte    "Elmos Semiconduc",0'             Elmos Semiconductor AG           
        byte    "Kllisre",0'             Kllisre
        byte    "Shenzhen Winconw",0'             Shenzhen Winconway Technology           
        byte    "Shenzhen Xingmem",0'             Shenzhen Xingmem Technology Corp           
        byte    "Gold Key Technol",0'             Gold Key Technology Co Ltd           
        byte    "Habana Labs Ltd",0'             Habana Labs Ltd
        byte    "Hoodisk Electron",0'             Hoodisk Electronics Co Ltd           
        byte    "SemsoTai (SZ) Te",0'             SemsoTai (SZ) Technology Co Ltd           
        byte    "OM Nanotech Pvt.",0'             OM Nanotech Pvt. Ltd           
        byte    "Shenzhen Zhifeng",0'             Shenzhen Zhifeng Weiye Technology           
        byte    "Xinshirui (Shenz",0'             Xinshirui (Shenzhen) Electronics Co           
        byte    "Guangzhou Zhong ",0'             Guangzhou Zhong Hao Tian Electronic           
        byte    "Shenzhen Longsys",0'             Shenzhen Longsys Electronics Co Ltd           
        byte    "Deciso B.V.",0'             Deciso B.V.
        byte    "Puya Semiconduct",0'             Puya Semiconductor (Shenzhen)           
        byte    "Shenzhen Veineda",0'             Shenzhen Veineda Technology Co Ltd           
        byte    "Antec Memory",0'             Antec Memory
        byte    "Cortus SAS",0'             Cortus SAS
        byte    "Dust Leopard",0'             Dust Leopard
        byte    "MyWo AS",0'             MyWo AS
        byte    "J&A Information ",0'             J&A Information Inc           
        byte    "Shenzhen JIEPEI ",0'             Shenzhen JIEPEI Technology Co Ltd           
        byte    "Heidelberg Unive",0'             Heidelberg University           
        byte    "Flexxon PTE Ltd",0'             Flexxon PTE Ltd
        byte    "Wiliot",0'             Wiliot
        byte    "Raysun Electroni",0'             Raysun Electronics International Ltd           
        byte    "Aquarius Product",0'             Aquarius Production Company LLC           
        byte    "MACNICA DHW LTDA",0'             MACNICA DHW LTDA
        byte    "Intelimem",0'             Intelimem
        byte    "Zbit Semiconduct",0'             Zbit Semiconductor Inc           
        byte    "Shenzhen Technol",0'             Shenzhen Technology Co Ltd           
        byte    "Signalchip",0'             Signalchip
        byte    "Shenzen Recadata",0'             Shenzen Recadata Storage Technology           
        byte    "Hyundai Technolo",0'             Hyundai Technology           
        byte    "Shanghai Fudi In",0'             Shanghai Fudi Investment Development           
        byte    "Aixi Technology",0'             Aixi Technology
        byte    "Tecon MT",0'             Tecon MT
        byte    "Onda Electric Co",0'             Onda Electric Co Ltd           
        byte    "Jinshen",0'             Jinshen
        byte    "Kimtigo Semicond",0'             Kimtigo Semiconductor (HK) Limited           
        byte    "IIT Madras",0'             IIT Madras
        byte    "Shenshan (Shenzh",0'             Shenshan (Shenzhen) Electronic           
        byte    "Hefei Core Stora",0'             Hefei Core Storage Electronic Limited           
        byte    "Colorful Technol",0'             Colorful Technology Ltd           
        byte    "Visenta (Xiamen)",0'             Visenta (Xiamen) Technology Co Ltd           
        byte    "Roa Logic BV",0'             Roa Logic BV
        byte    "NSITEXE Inc",0'             NSITEXE Inc
        byte    "Hong Kong Hyunio",0'             Hong Kong Hyunion Electronics           
        byte    "ASK Technology G",0'             ASK Technology Group Limited           
        byte    "GIGA-BYTE Techno",0'             GIGA-BYTE Technology Co Ltd           
        byte    "Terabyte Co Ltd",0'             Terabyte Co Ltd
        byte    "Hyundai Inc",0'             Hyundai Inc
        byte    "EXCELERAM",0'             EXCELERAM
        byte    "PsiKick",0'             PsiKick
        byte    "Netac Technology",0'             Netac Technology Co Ltd           
        byte    "PCCOOLER",0'             PCCOOLER
        byte    "Jiangsu Huacun E",0'             Jiangsu Huacun Electronic Technology           
        byte    "Shenzhen Micro I",0'             Shenzhen Micro Innovation Industry           
        byte    "Beijing Tongfang",0'             Beijing Tongfang Microelectronics Co           
        byte    "XZN Storage Tech",0'             XZN Storage Technology           
        byte    "ChipCraft Sp. z.",0'             ChipCraft Sp. z.o.o.           
        byte    "ALLFLASH Technol",0'             ALLFLASH Technology Limited           
        byte    "Foerd Technology",0'             Foerd Technology Co Ltd           
        byte    "KingSpec",0'             KingSpec
        byte    "Codasip GmbH",0'             Codasip GmbH
        byte    "SL Link Co Ltd",0'             SL Link Co Ltd
        byte    "Shenzhen Kefu Te",0'             Shenzhen Kefu Technology Co Limited           
        byte    "Shenzhen ZST Ele",0'             Shenzhen ZST Electronics Technology           
        byte    "Kyokuto Electron",0'             Kyokuto Electronic Inc           
        byte    "Warrior Technolo",0'             Warrior Technology           
        byte    "TRINAMIC Motion ",0'             TRINAMIC Motion Control GmbH & Co           
        byte    "PixelDisplay Inc",0'             PixelDisplay Inc
        byte    "Shenzhen Futian ",0'             Shenzhen Futian District Bo Yueda Elec           
        byte    "Richtek Power",0'             Richtek Power
        byte    "Shenzhen LianTen",0'             Shenzhen LianTeng Electronics Co Ltd           
        byte    "AITC Memory",0'             AITC Memory
        byte    "UNIC Memory Tech",0'             UNIC Memory Technology Co Ltd           
        byte    "Shenzhen Huafeng",0'             Shenzhen Huafeng Science Technology           
        byte    "CXMT",0'             CXMT
        byte    "Guangzhou Xinyi ",0'             Guangzhou Xinyi Heng Computer Trading Firm           
        byte    "SambaNova System",0'             SambaNova Systems           
        byte    "V-GEN",0'             V-GEN
        byte    "Jump Trading",0'             Jump Trading
        byte    "Ampere Computing",0'             Ampere Computing
        byte    "Shenzhen Zhongsh",0'             Shenzhen Zhongshi Technology Co Ltd           
        byte    "Shenzhen Zhongti",0'             Shenzhen Zhongtian Bozhong Technology           
        byte    "Tri-Tech Interna",0'             Tri-Tech International           
        byte    "Silicon Intergra",0'             Silicon Intergrated Systems Corporation           
        byte    "Shenzhen HongDin",0'             Shenzhen HongDingChen Information           
        byte    "Plexton Holdings",0'             Plexton Holdings Limited           
        byte    "AMS (Jiangsu Adv",0'             AMS (Jiangsu Advanced Memory Semi)           
        byte    "Wuhan Jing Tian ",0'             Wuhan Jing Tian Interconnected Tech Co           
        byte    "Axia Memory Tech",0'             Axia Memory Technology           
        byte    "Chipset Technolo",0'             Chipset Technology Holding Limited           
        byte    "Shenzhen Xinshid",0'             Shenzhen Xinshida Technology Co Ltd           
        byte    "Shenzhen Chuangs",0'             Shenzhen Chuangshifeida Technology           
        byte    "Guangzhou MiaoYu",0'             Guangzhou MiaoYuanJi Technology           
        byte    "ADVAN Inc",0'             ADVAN Inc
        byte    "Shenzhen Qianhai",0'             Shenzhen Qianhai Weishengda Electronic Commerce Company Ltd           
        byte    "Guangzhou Guang ",0'             Guangzhou Guang Xie Cheng Trading           
        byte    "StarRam Internat",0'             StarRam International Co Ltd           
        byte    "Shen Zhen XinShe",0'             Shen Zhen XinShenHua Tech Co Ltd           
        byte    "UltraMemory Inc",0'             UltraMemory Inc
        byte    "New Coastline Gl",0'             New Coastline Global Tech Industry Co           
        byte    "Sinker",0'             Sinker
        byte    "Diamond",0'             Diamond
        byte    "PUSKILL",0'             PUSKILL
        byte    "Guangzhou Hao Ji",0'             Guangzhou Hao Jia Ye Technology Co           
        byte    "Ming Xin Limited",0'             Ming Xin Limited
        byte    "Barefoot Network",0'             Barefoot Networks           
        byte    "Biwin Semiconduc",0'             Biwin Semiconductor (HK) Co Ltd           
        byte    "UD INFO Corporat",0'             UD INFO Corporation           
        byte    "Trek Technology ",0'             Trek Technology (S) PTE Ltd           
        byte    "Xiamen Kingblaze",0'             Xiamen Kingblaze Technology Co Ltd           
        byte    "Shenzhen Lomica ",0'             Shenzhen Lomica Technology Co Ltd           
        byte    "Nuclei System Te",0'             Nuclei System Technology Co Ltd           
        byte    "Wuhan Xun Zhan E",0'             Wuhan Xun Zhan Electronic Technology           
        byte    "Shenzhen Ingacom",0'             Shenzhen Ingacom Semiconductor Ltd           
        byte    "Zotac Technology",0'             Zotac Technology Ltd           
        byte    "Foxline",0'             Foxline
        byte    "Shenzhen Farasia",0'             Shenzhen Farasia Science Technology           
        byte    "Efinix Inc",0'             Efinix Inc
        byte    "Hua Nan San Xian",0'             Hua Nan San Xian Technology Co Ltd           
        byte    "Goldtech Electro",0'             Goldtech Electronics Co Ltd           
        byte    "Shanghai Han Ron",0'             Shanghai Han Rong Microelectronics Co           
        byte    "Shenzhen Zhonggu",0'             Shenzhen Zhongguang Yunhe Trading           
        byte    "Smart Shine(Qing",0'             Smart Shine(QingDao) Microelectronics           
        byte    "Thermaltake Tech",0'             Thermaltake Technology Co Ltd           
        byte    "Shenzhen O'Yang ",0'             Shenzhen O'Yang Maile Technology Ltd           
        byte    "UPMEM",0'             UPMEM
        byte    "Chun Well Techno",0'             Chun Well Technology Holding Limited           
        byte    "Astera Labs Inc",0'             Astera Labs Inc
        byte    "Winconway",0'             Winconway
        byte    "Advantech Co Ltd",0'             Advantech Co Ltd
        byte    "Chengdu Fengcai ",0'             Chengdu Fengcai Electronic Technology           
        byte    "The Boeing Compa",0'             The Boeing Company           
        byte    "Blaize Inc",0'             Blaize Inc
        byte    "Ramonster Techno",0'             Ramonster Technology Co Ltd           
        byte    "Wuhan Naonongmai",0'             Wuhan Naonongmai Technology Co Ltd           
        byte    "Shenzhen Hui Shi",0'             Shenzhen Hui ShingTong Technology           
        byte    "Yourlyon",0'             Yourlyon
        byte    "Fabu Technology",0'             Fabu Technology
        byte    "Shenzhen Yikeshe",0'             Shenzhen Yikesheng Technology Co Ltd           
        byte    "NOR-MEM",0'             NOR-MEM
        byte    "Cervoz Co Ltd",0'             Cervoz Co Ltd
        byte    "Bitmain Technolo",0'             Bitmain Technologies Inc.           
        byte    "Facebook Inc",0'             Facebook Inc
        byte    "Shenzhen Longsys",0'             Shenzhen Longsys Electronics Co Ltd           
        byte    "Guangzhou Siye E",0'             Guangzhou Siye Electronic Technology           
        byte    "Silergy",0'             Silergy
        byte    "Adamway",0'             Adamway
        byte    "PZG",0'             PZG
        byte    "Shenzhen King Po",0'             Shenzhen King Power Electronics           
        byte    "Guangzhou ZiaoFu",0'             Guangzhou ZiaoFu Tranding Co Ltd           
        byte    "Shenzhen SKIHOTA",0'             Shenzhen SKIHOTAR Semiconductor           
        byte    "PulseRain Techno",0'             PulseRain Technology           
        byte    "Seeker Technolog",0'             Seeker Technology Limited           
        byte    "Shenzhen OSCOO T",0'             Shenzhen OSCOO Tech Co Ltd           
        byte    "Shenzhen Yze Tec",0'             Shenzhen Yze Technology Co Ltd           
        byte    "Shenzhen Jieshuo",0'             Shenzhen Jieshuo Electronic Commerce           
        byte    "Gazda",0'             Gazda
        byte    "Hua Wei Technolo",0'             Hua Wei Technology Co Ltd           
        byte    "Esperanto Techno",0'             Esperanto Technologies           
        byte    "JinSheng Electro",0'             JinSheng Electronic (Shenzhen) Co Ltd           
        byte    "Shenzhen Shi Bol",0'             Shenzhen Shi Bolunshuai Technology           
        byte    "Shanghai Rui Zua",0'             Shanghai Rui Zuan Information Tech           
        byte    "Fraunhofer IIS",0'             Fraunhofer IIS
        byte    "Kandou Bus SA",0'             Kandou Bus SA
        byte    "Acer",0'             Acer
        byte    "Artmem Technolog",0'             Artmem Technology Co Ltd           
        byte    "Gstar Semiconduc",0'             Gstar Semiconductor Co Ltd           
        byte    "ShineDisk",0'             ShineDisk
        byte    "Shenzhen CHN Tec",0'             Shenzhen CHN Technology Co Ltd           
        byte    "UnionChip Semico",0'             UnionChip Semiconductor Co Ltd           
        byte    "Tanbassh",0'             Tanbassh
        byte    "Shenzhen Tianyu ",0'             Shenzhen Tianyu Jieyun Intl Logistics           
        byte    "MCLogic Inc",0'             MCLogic Inc
        byte    "Eorex Corporatio",0'             Eorex Corporation           
        byte    "Arm Technology (",0'             Arm Technology (China) Co Ltd           
        byte    "Lexar Co Limited",0'             Lexar Co Limited
        byte    "QinetiQ Group pl",0'             QinetiQ Group plc           
        byte    "Exascend",0'             Exascend
        byte    "Hong Kong Hyunio",0'             Hong Kong Hyunion Electronics Co Ltd           
        byte    "Shenzhen Banghon",0'             Shenzhen Banghong Electronics Co Ltd           
        byte    "MBit Wireless In",0'             MBit Wireless Inc           
        byte    "Hex Five Securit",0'             Hex Five Security Inc           
        byte    "ShenZhen Juhor P",0'             ShenZhen Juhor Precision Tech Co Ltd           
        byte    "Shenzhen Reeinno",0'             Shenzhen Reeinno Technology Co Ltd           
        byte    "ABIT Electronics",0'             ABIT Electronics (Shenzhen) Co Ltd           
        byte    "Semidrive",0'             Semidrive
        byte    "MyTek Electronic",0'             MyTek Electronics Corp           
        byte    "Wxilicon Technol",0'             Wxilicon Technology Co Ltd           
        byte    "Shenzhen Meixin ",0'             Shenzhen Meixin Electronics Ltd           
        byte    "Ghost Wolf",0'             Ghost Wolf
        byte    "LiSion Technolog",0'             LiSion Technologies Inc           
        byte    "Power Active Co ",0'             Power Active Co Ltd           
        byte    "Pioneer High Fid",0'             Pioneer High Fidelity Taiwan Co. Ltd           
        byte    "LuoSilk",0'             LuoSilk
        byte    "Shenzhen Chuangs",0'             Shenzhen Chuangshifeida Technology           
        byte    "Black Sesame Tec",0'             Black Sesame Technologies Inc           
        byte    "Jiangsu Xinsheng",0'             Jiangsu Xinsheng Intelligent Technology           
        byte    "MLOONG",0'             MLOONG
        byte    "Quadratica LLC",0'             Quadratica LLC
        byte    "Anpec Electronic",0'             Anpec Electronics           
        byte    "Xi'an Morebeck S",0'             Xi'an Morebeck Semiconductor Tech Co           
        byte    "Kingbank Technol",0'             Kingbank Technology Co Ltd           
        byte    "ITRenew Inc",0'             ITRenew Inc
        byte    "Shenzhen Eaget I",0'             Shenzhen Eaget Innovation Tech Ltd           
        byte    "Jazer",0'             Jazer
        byte    "Xiamen Semicondu",0'             Xiamen Semiconductor Investment Group           
        byte    "Guangzhou Longda",0'             Guangzhou Longdao Network Tech Co           
        byte    "Shenzhen Futian ",0'             Shenzhen Futian SEC Electronic Market           
        byte    "Allegro Microsys",0'             Allegro Microsystems LLC           
        byte    "Hunan RunCore In",0'             Hunan RunCore Innovation Technology           
        byte    "C-Corsa Technolo",0'             C-Corsa Technology           
        byte    "Zhuhai Chuangfei",0'             Zhuhai Chuangfeixin Technology Co Ltd           
        byte    "Beijing InnoMem ",0'             Beijing InnoMem Technologies Co Ltd           
        byte    "YooTin",0'             YooTin
        byte    "Shenzhen Pengxio",0'             Shenzhen Pengxiong Technology Co Ltd           
        byte    "Dongguan Yingban",0'             Dongguan Yingbang Commercial Trading Co           
        byte    "Shenzhen Ronisys",0'             Shenzhen Ronisys Electronics Co Ltd           
        byte    "Hongkong Xinlan ",0'             Hongkong Xinlan Guangke Co Ltd           
        byte    "Apex Microelectr",0'             Apex Microelectronics Co Ltd           
        byte    "Beijing Hongda J",0'             Beijing Hongda Jinming Technology Co Ltd           
        byte    "Ling Rui Technol",0'             Ling Rui Technology (Shenzhen) Co Ltd           
        byte    "Hongkong Hyunion",0'             Hongkong Hyunion Electronics Co Ltd           
        byte    "Starsystems Inc",0'             Starsystems Inc
        byte    "Shenzhen Yingjia",0'             Shenzhen Yingjiaxun Industrial Co Ltd           
        byte    "Dongguan Crown C",0'             Dongguan Crown Code Electronic Commerce           
        byte    "Monolithic Power",0'             Monolithic Power Systems Inc           
        byte    "WuHan SenNaiBo E",0'             WuHan SenNaiBo E-Commerce Co Ltd           
        byte    "Hangzhou Hikstor",0'             Hangzhou Hikstorage Technology Co           
        byte    "Shenzhen Goodix ",0'             Shenzhen Goodix Technology Co Ltd           
        byte    "Aigo Electronic ",0'             Aigo Electronic Technology Co Ltd           
        byte    "Hefei Konsemi St",0'             Hefei Konsemi Storage Technology Co Ltd           
        byte    "Cactus Technolog",0'             Cactus Technologies Limited           
        byte    "DSIN",0'             DSIN
        byte    "Blu Wireless Tec",0'             Blu Wireless Technology           
        byte    "Nanjing UCUN Tec",0'             Nanjing UCUN Technology Inc           
        byte    "Acacia Communica",0'             Acacia Communications           
        byte    "Beijinjinshengyi",0'             Beijinjinshengyihe Technology Co Ltd           
        byte    "Zyzyx",0'             Zyzyx
        byte    "C-SKY Microsyste",0'             C-SKY Microsystems Co Ltd           
        byte    "Shenzhen Hystou ",0'             Shenzhen Hystou Technology Co Ltd           
        byte    "Syzexion",0'             Syzexion
        byte    "Kembona",0'             Kembona
        byte    "Qingdao Thundero",0'             Qingdao Thunderobot Technology Co Ltd           
        byte    "Morse Micro",0'             Morse Micro
        byte    "Shenzhen Envida ",0'             Shenzhen Envida Technology Co Ltd           
        byte    "UDStore Solution",0'             UDStore Solution Limited           
        byte    "Shunlie",0'             Shunlie
        byte    "Shenzhen Xin Hon",0'             Shenzhen Xin Hong Rui Tech Ltd           
        byte    "Shenzhen Yze Tec",0'             Shenzhen Yze Technology Co Ltd           
        byte    "Shenzhen Huang P",0'             Shenzhen Huang Pu He Xin Technology           
        byte    "Xiamen Pengpai M",0'             Xiamen Pengpai Microelectronics Co Ltd           
        byte    "JISHUN",0'             JISHUN
        byte    "Shenzhen WODPOSI",0'             Shenzhen WODPOSIT Technology Co           
        byte    "Unistar",0'             Unistar
        byte    "UNICORE Electron",0'             UNICORE Electronic (Suzhou) Co Ltd           
        byte    "Axonne Inc",0'             Axonne Inc
        byte    "Shenzhen SOVEREC",0'             Shenzhen SOVERECA Technology Co           
        byte    "Dire Wolf",0'             Dire Wolf
        byte    "Whampoa Core Tec",0'             Whampoa Core Technology Co Ltd           
        byte    "CSI Halbleiter G",0'             CSI Halbleiter GmbH           
        byte    "ONE Semiconducto",0'             ONE Semiconductor           
        byte    "SimpleMachines I",0'             SimpleMachines Inc           
        byte    "Shenzhen Chengyi",0'             Shenzhen Chengyi Qingdian Electronic           
        byte    "Shenzhen Xinlian",0'             Shenzhen Xinlianxin Network Technology           
        byte    "Vayyar Imaging L",0'             Vayyar Imaging Ltd           
        byte    "Paisen Network T",0'             Paisen Network Technology Co Ltd           
        byte    "Shenzhen Fengwen",0'             Shenzhen Fengwensi Technology Co Ltd           
        byte    "Caplink Technolo",0'             Caplink Technology Limited           
        byte    "JJT Solution Co ",0'             JJT Solution Co Ltd           
        byte    "HOSIN Global Ele",0'             HOSIN Global Electronics Co Ltd           
        byte    "Shenzhen KingDis",0'             Shenzhen KingDisk Century Technology           
        byte    "SOYO",0'             SOYO
        byte    "DIT Technology C",0'             DIT Technology Co Ltd           
        byte    "iFound",0'             iFound
        byte    "Aril Computer Co",0'             Aril Computer Company           
        byte    "ASUS",0'             ASUS
        byte    "Shenzhen Ruiying",0'             Shenzhen Ruiyingtong Technology Co           
        byte    "HANA Micron",0'             HANA Micron
        byte    "RANSOR",0'             RANSOR
        byte    "Axiado Corporati",0'             Axiado Corporation           
        byte    "Tesla Corporatio",0'             Tesla Corporation           
        byte    "Pingtouge (Shang",0'             Pingtouge (Shanghai) Semiconductor Co           
        byte    "S3Plus Technolog",0'             S3Plus Technologies SA           
        byte    "Integrated Silic",0'             Integrated Silicon Solution Israel Ltd           
        byte    "GreenWaves Techn",0'             GreenWaves Technologies           
        byte    "NUVIA Inc",0'             NUVIA Inc
        byte    "Guangzhou Shuvrw",0'             Guangzhou Shuvrwine Technology Co           
        byte    "Shenzhen Hangshu",0'             Shenzhen Hangshun Chip Technology           
        byte    "Chengboliwei Ele",0'             Chengboliwei Electronic Business           
        byte    "Kowin Technology",0'             Kowin Technology HK Limited           
        byte    "Euronet Technolo",0'             Euronet Technology Inc           
        byte    "SCY",0'             SCY
        byte    "Shenzhen Xinhong",0'             Shenzhen Xinhongyusheng Electrical           
        byte    "PICOCOM",0'             PICOCOM
        byte    "Shenzhen Toooogo",0'             Shenzhen Toooogo Memory Technology           
        byte    "VLSI Solution",0'             VLSI Solution
        byte    "Costar Electroni",0'             Costar Electronics Inc           
        byte    "Shenzhen Huatop ",0'             Shenzhen Huatop Technology Co Ltd           
        byte    "Inspur Electroni",0'             Inspur Electronic Information Industry           
        byte    "Shenzhen Boyuan ",0'             Shenzhen Boyuan Computer Technology           
        byte    "Beijing Welldisk",0'             Beijing Welldisk Electronics Co Ltd           
        byte    "Suzhou EP Semico",0'             Suzhou EP Semicon Co Ltd           
        byte    "Zhejiang Dahua M",0'             Zhejiang Dahua Memory Technology           
        byte    "Virtu Financial",0'             Virtu Financial
        byte    "Datotek Internat",0'             Datotek International Co Ltd           
        byte    "Telecom and Micr",0'             Telecom and Microelectronics Industries           
        byte    "Echow Technology",0'             Echow Technology Ltd           
        byte    "APEX-INFO",0'             APEX-INFO
        byte    "Yingpark",0'             Yingpark
        byte    "Shenzhen Bigway ",0'             Shenzhen Bigway Tech Co Ltd           
        byte    "Beijing Haawking",0'             Beijing Haawking Technology Co Ltd           
        byte    "Open HW Group",0'             Open HW Group
        byte    "JHICC",0'             JHICC
        byte    "ncoder AG",0'             ncoder AG
        byte    "ThinkTech Inform",0'             ThinkTech Information Technology Co           
        byte    "Shenzhen Chixing",0'             Shenzhen Chixingzhe Technology Co Ltd           
        byte    "Biao Ram Technol",0'             Biao Ram Technology Co Ltd           
        byte    "Shenzhen Kaizhuo",0'             Shenzhen Kaizhuoyue Electronics Co Ltd           
        byte    "Shenzhen YC Stor",0'             Shenzhen YC Storage Technology Co Ltd           
        byte    "Shenzhen Chixing",0'             Shenzhen Chixingzhe Technology Co           
        byte    "Wink Semiconduct",0'             Wink Semiconductor (Shenzhen) Co Ltd           
        byte    "AISTOR",0'             AISTOR
        byte    "Palma Ceia SemiD",0'             Palma Ceia SemiDesign           
        byte    "EM Microelectron",0'             EM Microelectronic-Marin SA           
        byte    "Shenzhen Monarch",0'             Shenzhen Monarch Memory Technology           
        byte    "Reliance Memory ",0'             Reliance Memory Inc           
        byte    "Jesis",0'             Jesis
        byte    "Espressif System",0'             Espressif Systems (Shanghai) Co Ltd           
        byte    "Shenzhen Sati Sm",0'             Shenzhen Sati Smart Technology Co Ltd           
        byte    "NeuMem Co Ltd",0'             NeuMem Co Ltd
        byte    "Lifelong",0'             Lifelong
        byte    "Beijing Oitech T",0'             Beijing Oitech Technology Co Ltd           
        byte    "Groupe LDLC",0'             Groupe LDLC
        byte    "Semidynamics Tec",0'             Semidynamics Technology Services SLU           
        byte    "swordbill",0'             swordbill
        byte    "YIREN",0'             YIREN
        byte    "Shenzhen Yinxian",0'             Shenzhen Yinxiang Technology Co Ltd           
        byte    "PoweV Electronic",0'             PoweV Electronic Technology Co Ltd           
        byte    "LEORICE",0'             LEORICE
        byte    "Waymo LLC",0'             Waymo LLC
        byte    "Ventana Micro Sy",0'             Ventana Micro Systems           
        byte    "Hefei Guangxin M",0'             Hefei Guangxin Microelectronics Co Ltd           
        byte    "Shenzhen Sooner ",0'             Shenzhen Sooner Industrial Co Ltd           
        byte    "Horizon Robotics",0'             Horizon Robotics
        byte    "Tangem AG",0'             Tangem AG
        byte    "FuturePath Techn",0'             FuturePath Technology (Shenzhen) Co           
        byte    "RC Module",0'             RC Module
        byte    "Timetec Internat",0'             Timetec International Inc           
        byte    "ICMAX Technologi",0'             ICMAX Technologies Co Limited           
        byte    "Lynxi Technologi",0'             Lynxi Technologies Ltd Co           
        byte    "Guangzhou Taisup",0'             Guangzhou Taisupanke Computer Equipment           
        byte    "Ceremorphic Inc",0'             Ceremorphic Inc
        byte    "Biwin Storage Te",0'             Biwin Storage Technology Co Ltd           
        byte    "Beijing ESWIN Co",0'             Beijing ESWIN Computing Technology           
        byte    "WeForce Co Ltd",0'             WeForce Co Ltd
        byte    "Shenzhen Fanxian",0'             Shenzhen Fanxiang Information Technology           
        byte    "Unisoc",0'             Unisoc
        byte    "YingChu",0'             YingChu
        byte    "GUANCUN",0'             GUANCUN
        byte    "IPASON",0'             IPASON
        byte    "Ayar Labs",0'             Ayar Labs
        byte    "Amazon",0'             Amazon
        byte    "Shenzhen Xinxins",0'             Shenzhen Xinxinshun Technology Co           
        byte    "Galois Inc",0'             Galois Inc
        byte    "Ubilite Inc",0'             Ubilite Inc
        byte    "Shenzhen Quanxin",0'             Shenzhen Quanxing Technology Co Ltd           
        byte    "Group RZX Techno",0'             Group RZX Technology LTDA           
        byte    "Yottac Technolog",0'             Yottac Technology (XI'AN) Cooperation           
        byte    "Shenzhen RuiRen ",0'             Shenzhen RuiRen Technology Co Ltd           
        byte    "Group Star Techn",0'             Group Star Technology Co Ltd           
        byte    "RWA (Hong Kong) ",0'             RWA (Hong Kong) Ltd           
        byte    "Genesys Logic In",0'             Genesys Logic Inc           
        byte    "T3 Robotics Inc.",0'             T3 Robotics Inc.
        byte    "Biostar Microtec",0'             Biostar Microtech International Corp           
        byte    "Shenzhen SXmicro",0'             Shenzhen SXmicro Technology Co Ltd           
        byte    "Shanghai Yili Co",0'             Shanghai Yili Computer Technology Co           
        byte    "Zhixin Semicoduc",0'             Zhixin Semicoducotor Co Ltd           
        byte    "uFound",0'             uFound
        byte    "Aigo Data Securi",0'             Aigo Data Security Technology Co. Ltd           
        byte    ".GXore Technolog",0'             .GXore Technologies           
        byte    "Shenzhen Pradeon",0'             Shenzhen Pradeon Intelligent Technology           
        byte    "Power LSI",0'             Power LSI
        byte    "PRIME",0'             PRIME
        byte    "Shenzhen Juyang ",0'             Shenzhen Juyang Innovative Technology           
        byte    "CERVO",0'             CERVO
        byte    "SiEngine Technol",0'             SiEngine Technology Co., Ltd.           
        byte    "Beijing Unigroup",0'             Beijing Unigroup Tsingteng MicroSystem           
        byte    "Brainsao GmbH",0'             Brainsao GmbH
        byte    "Credo Technology",0'             Credo Technology Group Ltd           
        byte    "Shanghai Biren T",0'             Shanghai Biren Technology Co Ltd           
        byte    "Nucleu Semicondu",0'             Nucleu Semiconductor           
        byte    "Shenzhen Guangsh",0'             Shenzhen Guangshuo Electronics Co Ltd           
        byte    "ZhongsihangTechn",0'             ZhongsihangTechnology Co Ltd           
        byte    "Suzhou Mainshine",0'             Suzhou Mainshine Electronic Co Ltd.           
        byte    "Guangzhou Riss E",0'             Guangzhou Riss Electronic Technology           
        byte    "Shenzhen Cloud S",0'             Shenzhen Cloud Security Storage Co           
        byte    "ROG",0'             ROG
        byte    "Perceive",0'             Perceive
        byte    "e-peas",0'             e-peas
        byte    "Fraunhofer IPMS",0'             Fraunhofer IPMS
        byte    "Shenzhen Daxinla",0'             Shenzhen Daxinlang Electronic Tech Co           
        byte    "Abacus Periphera",0'             Abacus Peripherals Private Limited           
        byte    "OLOy Technology",0'             OLOy Technology
        byte    "Wuhan P&S Semico",0'             Wuhan P&S Semiconductor Co Ltd           
        byte    "Sitrus Technolog",0'             Sitrus Technology           
        byte    "AnHui Conner Sto",0'             AnHui Conner Storage Co Ltd           
        byte    "Rochester Electr",0'             Rochester Electronics           
        byte    "Wuxi Smart Memor",0'             Wuxi Smart Memories Technologies Co           
        byte    "Star Memory",0'             Star Memory
        byte    "Agile Memory Tec",0'             Agile Memory Technology Co Ltd           
        byte    "MEJEC",0'             MEJEC
        byte    "Rockchip Electro",0'             Rockchip Electronics Co Ltd           
        byte    "Dongguan Guanma ",0'             Dongguan Guanma e-commerce Co Ltd           
        byte    "Rayson Hi-Tech (",0'             Rayson Hi-Tech (SZ) Limited           
        byte    "MINRES Technolog",0'             MINRES Technologies GmbH           
        byte    "Himax Technologi",0'             Himax Technologies Inc           
        byte    "Shenzhen Cwinner",0'             Shenzhen Cwinner Technology Co Ltd           
        byte    "Tecmiyo",0'             Tecmiyo
        byte    "Shenzhen Suhuicu",0'             Shenzhen Suhuicun Technology Co Ltd           
        byte    "Vickter Electron",0'             Vickter Electronics Co. Ltd.           
        byte    "lowRISC",0'             lowRISC
        byte    "EXEGate FZE",0'             EXEGate FZE
        byte    "Shenzhen 9 Chapt",0'             Shenzhen 9 Chapter Technologies Co           
        byte    "Addlink",0'             Addlink
        byte    "Starsway",0'             Starsway
        byte    "Pensando Systems",0'             Pensando Systems Inc.           
        byte    "AirDisk",0'             AirDisk
        byte    "Shenzhen Speedmo",0'             Shenzhen Speedmobile Technology Co           
        byte    "PEZY Computing",0'             PEZY Computing
        byte    "Extreme Engineer",0'             Extreme Engineering Solutions Inc           
        byte    "Shangxin Technol",0'             Shangxin Technology Co Ltd           
        byte    "Shanghai Zhaoxin",0'             Shanghai Zhaoxin Semiconductor Co           
        byte    "Xsight Labs Ltd",0'             Xsight Labs Ltd
        byte    "Hangzhou Hikstor",0'             Hangzhou Hikstorage Technology Co           
        byte    "Dell Technologie",0'             Dell Technologies           
        byte    "Guangdong StarFi",0'             Guangdong StarFive Technology Co           
        byte    "TECOTON",0'             TECOTON
        byte    "Abko Co Ltd",0'             Abko Co Ltd
        byte    "Shenzhen Feisrik",0'             Shenzhen Feisrike Technology Co Ltd           
        byte    "Shenzhen Sunhome",0'             Shenzhen Sunhome Electronics Co Ltd           
        byte    "Global Mixed-mod",0'             Global Mixed-mode Technology Inc           
        byte    "Shenzhen Weien E",0'             Shenzhen Weien Electronics Co. Ltd.           
        byte    "Shenzhen Cooyes ",0'             Shenzhen Cooyes Technology Co Ltd           
        byte    "Keymos Electroni",0'             Keymos Electronics Co., Limited           
        byte    "E-Rockic Technol",0'             E-Rockic Technology Company Limited           
        byte    "Aerospace Scienc",0'             Aerospace Science Memory Shenzhen           
        byte    "Shenzhen Quanji ",0'             Shenzhen Quanji Technology Co Ltd           
        byte    "Dukosi",0'             Dukosi
        byte    "Maxell Corporati",0'             Maxell Corporation of America           
        byte    "Shenshen Xinxint",0'             Shenshen Xinxintao Electronics Co Ltd           
        byte    "Zhuhai Sanxia Se",0'             Zhuhai Sanxia Semiconductor Co Ltd           
        byte    "Groq Inc",0'             Groq Inc
        byte    "AstraTek",0'             AstraTek
        byte    "Shenzhen Xinyuze",0'             Shenzhen Xinyuze Technology Co Ltd           
        byte    "All Bit Semicond",0'             All Bit Semiconductor           
        byte    "ACFlow",0'             ACFlow
        byte    "Shenzhen Sipeed ",0'             Shenzhen Sipeed Technology Co Ltd           
        byte    "Linzhi Hong Kong",0'             Linzhi Hong Kong Co Limited           
        byte    "Supreme Wise Lim",0'             Supreme Wise Limited           
        byte    "Blue Cheetah Ana",0'             Blue Cheetah Analog Design Inc           
        byte    "Hefei Laiku Tech",0'             Hefei Laiku Technology Co Ltd           
        byte    "Zord",0'             Zord
        byte    "SBO Hearing A/S",0'             SBO Hearing A/S
        byte    "Regent Sharp Int",0'             Regent Sharp International Limited           
        byte    "Permanent Potent",0'             Permanent Potential Limited           
        byte    "Creative World I",0'             Creative World International Limited           
        byte    "Base Creation In",0'             Base Creation International Limited           
        byte    "Shenzhen Zhixin ",0'             Shenzhen Zhixin Chuanglian Technology           
        byte    "Protected Logic ",0'             Protected Logic Corporation           
        byte    "Sabrent",0'             Sabrent
        byte    "Union Memory",0'             Union Memory
        byte    "NEUCHIPS Corpora",0'             NEUCHIPS Corporation           
        byte    "Ingenic Semicond",0'             Ingenic Semiconductor Co Ltd           
        byte    "SiPearl",0'             SiPearl
        byte    "Shenzhen Actseno",0'             Shenzhen Actseno Information Technology           
        byte    "RIVAI Technologi",0'             RIVAI Technologies (Shenzhen) Co Ltd           
        byte    "Shenzhen Sunny T",0'             Shenzhen Sunny Technology Co Ltd           
        byte    "Cott Electronics",0'             Cott Electronics Ltd           
        byte    "Shanghai Synsens",0'             Shanghai Synsense Technologies Co Ltd           
        byte    "Shenzhen Jintang",0'             Shenzhen Jintang Fuming Optoelectronics           
        byte    "CloudBEAR LLC",0'             CloudBEAR LLC
        byte    "Emzior, LLC",0'             Emzior, LLC
        byte    "Ehiway Microelec",0'             Ehiway Microelectronic Science Tech Co           
        byte    "UNIM Innovation ",0'             UNIM Innovation Technology (Wu XI)           
        byte    "GDRAMARS",0'             GDRAMARS
        byte    "Meminsights Tech",0'             Meminsights Technology           
        byte    "Zhuzhou Hongda E",0'             Zhuzhou Hongda Electronics Corp Ltd           
        byte    "Luminous Computi",0'             Luminous Computing Inc           
        byte    "PROXMEM",0'             PROXMEM
        byte    "Draper Labs",0'             Draper Labs
        byte    "ORICO Technologi",0'             ORICO Technologies Co. Ltd.           
        byte    "Space Exploratio",0'             Space Exploration Technologies Corp           
        byte    "AONDEVICES Inc",0'             AONDEVICES Inc
        byte    "Shenzhen Netforw",0'             Shenzhen Netforward Micro Electronic           
        byte    "Syntacore Ltd",0'             Syntacore Ltd
        byte    "Shenzhen Secmem ",0'             Shenzhen Secmem Microelectronics Co           
        byte    "ONiO As",0'             ONiO As
        byte    "Shenzhen Peladn ",0'             Shenzhen Peladn Technology Co Ltd           
        byte    "O-Cubes Shanghai",0'             O-Cubes Shanghai Microelectronics           
        byte    "ASTC",0'             ASTC
        byte    "UMIS",0'             UMIS
        byte    "Paradromics",0'             Paradromics
        byte    "Sinh Micro Co Lt",0'             Sinh Micro Co Ltd           
        byte    "Metorage Semicon",0'             Metorage Semiconductor Technology Co           
        byte    "Aeva Inc",0'             Aeva Inc
        byte    "HongKong Hyunion",0'             HongKong Hyunion Electronics Co Ltd           
        byte    "China Flash Co L",0'             China Flash Co Ltd           
        byte    "Sunplus Technolo",0'             Sunplus Technology Co Ltd           
        byte    "Idaho Scientific",0'             Idaho Scientific
        byte    "Suzhou SF Micro ",0'             Suzhou SF Micro Electronics Co Ltd           
        byte    "IMEX Cap AG",0'             IMEX Cap AG
        byte    "Fitipower Integr",0'             Fitipower Integrated Technology Co Ltd           
        byte    "ShenzhenWooacme ",0'             ShenzhenWooacme Technology Co Ltd           
        byte    "KeepData Origina",0'             KeepData Original Chips           
        byte    "Rivos Inc",0'             Rivos Inc
        byte    "Big Innovation C",0'             Big Innovation Company Limited           
        byte    "Wuhan YuXin Semi",0'             Wuhan YuXin Semiconductor Co Ltd           
        byte    "United Memory Te",0'             United Memory Technology (Jiangsu)           
        byte    "PQShield Ltd",0'             PQShield Ltd
        byte    "ArchiTek Corpora",0'             ArchiTek Corporation           
        byte    "ShenZhen AZW Tec",0'             ShenZhen AZW Technology Co Ltd           
        byte    "Hengchi Zhixin (",0'             Hengchi Zhixin (Dongguan) Technology           
        byte    "Eggtronic Engine",0'             Eggtronic Engineering Spa           
        byte    "Fusontai Technol",0'             Fusontai Technology           
        byte    "PULP Platform",0'             PULP Platform
        byte    "Koitek Electroni",0'             Koitek Electronic Technology (Shenzhen) Co           
        byte    "Shenzhen Jiteng ",0'             Shenzhen Jiteng Network Technology Co           
        byte    "Aviva Links Inc",0'             Aviva Links Inc
        byte    "Trilinear Techno",0'             Trilinear Technologies Inc           
        byte    "Shenzhen Develop",0'             Shenzhen Developer Microelectronics Co           
        byte    "Guangdong OPPO M",0'             Guangdong OPPO Mobile Telecommunication           
        byte    "Akeana",0'             Akeana
        byte    "Lyczar",0'             Lyczar
        byte    "Shenzhen Qiji Te",0'             Shenzhen Qiji Technology Co Ltd           
        byte    "Shenzhen Shangzh",0'             Shenzhen Shangzhaoyuan Technology           
        byte    "Han Stor",0'             Han Stor
        byte    "China Micro Semi",0'             China Micro Semicon Co., Ltd.           
        byte    "Shenzhen Zhuqin ",0'             Shenzhen Zhuqin Technology Co Ltd           
        byte    "Shanghai Ningyua",0'             Shanghai Ningyuan Electronic Technology           
        byte    "Auradine",0'             Auradine
        byte    "Suzhou Yishuo El",0'             Suzhou Yishuo Electronics Co Ltd           
        byte    "Faurecia Clarion",0'             Faurecia Clarion Electronics           
        byte    "SiMa Technologie",0'             SiMa Technologies           
        byte    "CFD Sales Inc",0'             CFD Sales Inc
        byte    "Suzhou Comay Inf",0'             Suzhou Comay Information Co Ltd           
        byte    "Yentek",0'             Yentek
        byte    "Qorvo Inc",0'             Qorvo Inc
        byte    "Shenzhen Youzhi ",0'             Shenzhen Youzhi Computer Technology           
        byte    "Sychw Technology",0'             Sychw Technology (Shenzhen) Co Ltd           
        byte    "MK Founder Techn",0'             MK Founder Technology Co Ltd           
        byte    "Siliconwaves Tec",0'             Siliconwaves Technologies Co Ltd           
        byte    "Hongkong Hyunion",0'             Hongkong Hyunion Electronics Co Ltd           
        byte    "Shenzhen Xinxinz",0'             Shenzhen Xinxinzhitao Electronics Business           
        byte    "Shenzhen HenQi E",0'             Shenzhen HenQi Electronic Commerce Co           
        byte    "Shenzhen Jingyi ",0'             Shenzhen Jingyi Technology Co Ltd           
        byte    "Xiaohua Semicond",0'             Xiaohua Semiconductor Co. Ltd.           
        byte    "Shenzhen Dalu Se",0'             Shenzhen Dalu Semiconductor Technology           
        byte    "Shenzhen Ninespe",0'             Shenzhen Ninespeed Electronics Co Ltd           
        byte    "ICYC Semiconduct",0'             ICYC Semiconductor Co Ltd           
        byte    "Shenzhen Jaguar ",0'             Shenzhen Jaguar Microsystems Co Ltd           
        byte    "Beijing EC-Found",0'             Beijing EC-Founder Co Ltd           
        byte    "Shenzhen Taike I",0'             Shenzhen Taike Industrial Automation Co           
        byte    "Kalray SA",0'             Kalray SA
        byte    "Shanghai Iluvata",0'             Shanghai Iluvatar CoreX Semiconductor Co           
        byte    "Fungible Inc",0'             Fungible Inc
        byte    "Song Industria E",0'             Song Industria E Comercio de Eletronicos           
        byte    "DreamBig Semicon",0'             DreamBig Semiconductor Inc           
        byte    "ChampTek Electro",0'             ChampTek Electronics Corp           
        byte    "Fusontai Technol",0'             Fusontai Technology           
        byte    "Endress Hauser A",0'             Endress Hauser AG           
        byte    "altec ComputerSy",0'             altec ComputerSysteme GmbH           
        byte    "UltraRISC Techno",0'             UltraRISC Technology (Shanghai) Co Ltd           
        byte    "Shenzhen Jing Da",0'             Shenzhen Jing Da Kang Technology Co Ltd           
        byte    "Hangzhou Hongjun",0'             Hangzhou Hongjun Microelectronics Co Ltd           
        byte    "Pliops Ltd",0'             Pliops Ltd
        byte    "Cix Technology (",0'             Cix Technology (Shanghai) Co Ltd           
        byte    "TeraDevices Inc",0'             TeraDevices Inc
        byte    "SpacemiT (Hangzh",0'             SpacemiT (Hangzhou)Technology Co Ltd           
        byte    "InnoPhase loT In",0'             InnoPhase loT Inc           
        byte    "InnoPhase loT In",0'             InnoPhase loT Inc           
        byte    "Yunhight Microel",0'             Yunhight Microelectronics           
        byte    "Samnix",0'             Samnix
        byte    "HKC Storage Co L",0'             HKC Storage Co Ltd           
        byte    "Chiplego Technol",0'             Chiplego Technology (Shanghai) Co Ltd           
        byte    "StoreSkill",0'             StoreSkill
        byte    "Shenzhen Astou T",0'             Shenzhen Astou Technology Company           
        byte    "Guangdong LeafFi",0'             Guangdong LeafFive Technology Limited           
        byte    "Jin JuQuan",0'             Jin JuQuan
        byte    "Huaxuan Technolo",0'             Huaxuan Technology (Shenzhen) Co Ltd           
        byte    "Gigastone Corpor",0'             Gigastone Corporation           
        byte    "Kinsotin",0'             Kinsotin
        byte    "PengYing",0'             PengYing
        byte    "Shenzhen Xunhi T",0'             Shenzhen Xunhi Technology Co Ltd           
        byte    "FOXX Storage Inc",0'             FOXX Storage Inc
        byte    "Shanghai Belling",0'             Shanghai Belling Corporation Ltd           
        byte    "Glenfy Tech Co L",0'             Glenfy Tech Co Ltd           
        byte    "Sahasra Semicond",0'             Sahasra Semiconductors Pvt Ltd           
        byte    "Chongqing SeekWa",0'             Chongqing SeekWave Technology Co Ltd           
        byte    "Shenzhen Zhixing",0'             Shenzhen Zhixing Intelligent Manufacturing           
        byte    "Ethernovia",0'             Ethernovia
        byte    "Shenzhen Xinrong",0'             Shenzhen Xinrongda Technology Co Ltd           
        byte    "Hangzhou Clounix",0'             Hangzhou Clounix Technology Limited           
        byte    "JGINYUE",0'             JGINYUE
        byte    "Shenzhen Xinwei ",0'             Shenzhen Xinwei Semiconductor Co Ltd           
        byte    "COLORFIRE Techno",0'             COLORFIRE Technology Co Ltd           
        byte    "B LKE",0'             B LKE
        byte    "ZHUDIAN",0'             ZHUDIAN
        byte    "REECHO",0'             REECHO
        byte    "Enphase Energy I",0'             Enphase Energy Inc           
        byte    "Shenzhen Yingrui",0'             Shenzhen Yingrui Storage Technology Co Ltd           
        byte    "Shenzhen Sinomos",0'             Shenzhen Sinomos Semiconductor Technology           
        byte    "O2micro Internat",0'             O2micro International Limited           
        byte    "Axelera AI BV",0'             Axelera AI BV
        byte    "Silicon Legend T",0'             Silicon Legend Technology (Suzhou) Co Ltd           
        byte    "Suzhou Novosense",0'             Suzhou Novosense Microelectronics Co Ltd           
        byte    "Pirateman",0'             Pirateman
        byte    "Yangtze MasonSem",0'             Yangtze MasonSemi           
        byte    "Shanghai Yunsili",0'             Shanghai Yunsilicon Technology Co Ltd           
        byte    "Rayson",0'             Rayson
        byte    "Alphawave IP",0'             Alphawave IP
        byte    "Shenzhen Visions",0'             Shenzhen Visions Chip Electronic Technology           
        byte    "KYO Group",0'             KYO Group
        byte    "Shenzhen Aboison",0'             Shenzhen Aboison Technology Co Ltd           
        byte    "Shenzhen JingShe",0'             Shenzhen JingSheng Semiconducto Co Ltd           
        byte    "Shenzhen Dingshe",0'             Shenzhen Dingsheng Technology Co Ltd           
        byte    "EVAS Intelligenc",0'             EVAS Intelligence Co Ltd           
        byte    "Kaibright Electr",0'             Kaibright Electronic Technologies           
        byte    "Fraunhofer IMS",0'             Fraunhofer IMS
        byte    "Shenzhen Xinrui ",0'             Shenzhen Xinrui Renhe Technology           
        byte    "Beijing Vcore Te",0'             Beijing Vcore Technology Co Ltd           
        byte    "Silicon Innovati",0'             Silicon Innovation Technologies Co Ltd           
        byte    "Shenzhen Zhengxi",0'             Shenzhen Zhengxinda Technology Co Ltd           
        byte    "Shenzhen Remai E",0'             Shenzhen Remai Electronics Co Lttd           
        byte    "Shenzhen Xinruiy",0'             Shenzhen Xinruiyan Electronics Co Ltd           
        byte    "CEC Huada Electr",0'             CEC Huada Electronic Design Co Ltd           
        byte    "Westberry Techno",0'             Westberry Technology Inc           
        byte    "Tongxin Microele",0'             Tongxin Microelectronics Co Ltd           
        byte    "UNIM Semiconduct",0'             UNIM Semiconductor (Shang Hai) Co Ltd           
        byte    "Shenzhen Qiaowen",0'             Shenzhen Qiaowenxingyu Industrial Co Ltd           
        byte    "ICC",0'             ICC
        byte    "Enfabrica Corpor",0'             Enfabrica Corporation           
        byte    "Niobium Microsys",0'             Niobium Microsystems Inc           
        byte    "Xiaoli AI Electr",0'             Xiaoli AI Electronics (Shenzhen) Co Ltd           
        byte    "Silicon Mitus",0'             Silicon Mitus
        byte    "Ajiatek Inc",0'             Ajiatek Inc
        byte    "HomeNet",0'             HomeNet
        byte    "Shenzhen Shubang",0'             Shenzhen Shubang Technology Co Ltd           
        byte    "Exacta Technolog",0'             Exacta Technologies Ltd           
        byte    "Synology",0'             Synology
        byte    "Trium Elektronik",0'             Trium Elektronik Bilgi Islem San Ve Dis           
        byte    "Wuxi HippStor Te",0'             Wuxi HippStor Technology Co Ltd           
        byte    "SSCT",0'             SSCT
        byte    "Sichuan Heentai ",0'             Sichuan Heentai Semiconductor Co Ltd           
        byte    "Zhejiang Univers",0'             Zhejiang University           
        byte    "www.shingroup.cn",0'             www.shingroup.cn
        byte    "Suzhou Nano Mchi",0'             Suzhou Nano Mchip Technology Company           
        byte    "Feature Integrat",0'             Feature Integration Technology Inc           
        byte    "d-Matrix",0'             d-Matrix
        byte    "Golden Memory",0'             Golden Memory
        byte    "Qingdao Thundero",0'             Qingdao Thunderobot Technology Co Ltd           
        byte    "Shenzhen Tianxia",0'             Shenzhen Tianxiang Chuangxin Technology           
        byte    "HYPHY USA",0'             HYPHY USA
        byte    "Valkyrie",0'             Valkyrie
        byte    "Suzhou Hesetc El",0'             Suzhou Hesetc Electronic Technology Co           
        byte    "Hainan Zhongyunc",0'             Hainan Zhongyuncun Technology Co Ltd           
        byte    "Shenzhen Youshen",0'             Shenzhen Yousheng Bona Technology Co           
        byte    "Shenzhen Xinle C",0'             Shenzhen Xinle Chuang Technology Co           
        byte    "DEEPX",0'             DEEPX
        byte    "iStarChip CA LLC",0'             iStarChip CA LLC
        byte    "Shenzhen Vinread",0'             Shenzhen Vinreada Technology Co Ltd           
        byte    "Novatek Microele",0'             Novatek Microelectronics Corp           
        byte    "Chemgdu EG Techn",0'             Chemgdu EG Technology Co Ltd           
        byte    "AGI Technology",0'             AGI Technology
        byte    "Syntiant",0'             Syntiant
        byte    "AOC",0'             AOC
        byte    "GamePP",0'             GamePP
        byte    "Yibai Electronic",0'             Yibai Electronic Technologies           
        byte    "Hangzhou Renchen",0'             Hangzhou Rencheng Trading Co Ltd           
        byte    "HOGE Technology ",0'             HOGE Technology Co Ltd           
        byte    "United Micro Tec",0'             United Micro Technology (Shenzhen) Co           
        byte    "Fabric of Truth ",0'             Fabric of Truth Inc           
        byte    "Epitech",0'             Epitech
        byte    "Elitestek",0'             Elitestek
        byte    "Cornelis Network",0'             Cornelis Networks Inc           
        byte    "WingSemi Technol",0'             WingSemi Technologies Co Ltd           
        byte    "ForwardEdge ASIC",0'             ForwardEdge ASIC
        byte    "Beijing Future I",0'             Beijing Future Imprint Technology Co Ltd           
        byte    "Fine Made Microe",0'             Fine Made Microelectronics Group Co Ltd           
        byte    "Changxin Memory ",0'             Changxin Memory Technology (Shanghai)           
        byte    "Synconv",0'             Synconv
        byte    "MULTIUNIT",0'             MULTIUNIT
        byte    "Zero ASIC Corpor",0'             Zero ASIC Corporation           
        byte    "NTT Innovative D",0'             NTT Innovative Devices Corporation           
        byte    "Xbstor",0'             Xbstor
        byte    "Shenzhen South E",0'             Shenzhen South Electron Co Ltd           
        byte    "Iontra Inc",0'             Iontra Inc
        byte    "SIEFFI Inc",0'             SIEFFI Inc
        byte    "HK Winston Elect",0'             HK Winston Electronics Co Limited           
        byte    "Anhui SunChip Se",0'             Anhui SunChip Semiconductor Technology           
        byte    "HaiLa Technologi",0'             HaiLa Technologies Inc           
        byte    "AUTOTALKS",0'             AUTOTALKS
        byte    "Shenzhen Ranshuo",0'             Shenzhen Ranshuo Technology Co Limited           
        byte    "ScaleFlux",0'             ScaleFlux
        byte    "XC Memory",0'             XC Memory
        byte    "Guangzhou Beimu ",0'             Guangzhou Beimu Technology Co., Ltd           
        byte    "Rays Semiconduct",0'             Rays Semiconductor Nanjing Co Ltd           
        byte    "Milli-Centi Inte",0'             Milli-Centi Intelligence Technology Jiangsu           
        byte    "Zilia Technologi",0'             Zilia Technologioes           
        byte    "Incore Semicondu",0'             Incore Semiconductors           
        byte    "Kinetic Technolo",0'             Kinetic Technologies           
        byte    "Nanjing Houmo Te",0'             Nanjing Houmo Technology Co Ltd           
        byte    "Suzhou Yige Tech",0'             Suzhou Yige Technology Co Ltd           
        byte    "Shenzhen Techwin",0'             Shenzhen Techwinsemi Technology Co Ltd           
        byte    "Pure Array Techn",0'             Pure Array Technology (Shanghai) Co. Ltd           
        byte    "Shenzhen Techwin",0'             Shenzhen Techwinsemi Technology Udstore           
        byte    "RISE MODE",0'             RISE MODE
        byte    "NEWREESTAR",0'             NEWREESTAR
        byte    "Hangzhou Hualan ",0'             Hangzhou Hualan Microeletronique Co Ltd           
        byte    "Senscomm Semicon",0'             Senscomm Semiconductor Co Ltd           
        byte    "Holt Integrated ",0'             Holt Integrated Circuits           
        byte    "Tenstorrent Inc",0'             Tenstorrent Inc
        byte    "SkyeChip",0'             SkyeChip
        byte    "Guangzhou Kaishi",0'             Guangzhou Kaishile Trading Co Ltd           
        byte    "Jing Pai Digital",0'             Jing Pai Digital Technology (Shenzhen) Co           
        byte    "Memoritek",0'             Memoritek
        byte    "Zhejiang Hikstor",0'             Zhejiang Hikstor Technology Co Ltd           
        byte    "Memoritek PTE Lt",0'             Memoritek PTE Ltd           
        byte    "Longsailing Semi",0'             Longsailing Semiconductor Co Ltd           
        byte    "LX Semicon",0'             LX Semicon
        byte    "Shenzhen Techwin",0'             Shenzhen Techwinsemi Technology Co Ltd           
        byte    "AOC",0'             AOC
        byte    "GOEPEL Electroni",0'             GOEPEL Electronic GmbH           
        byte    "Shenzhen G-Bong ",0'             Shenzhen G-Bong Technology Co Ltd           
        byte    "Openedges Techno",0'             Openedges Technology Inc           
        byte    "EA Semi Shangahi",0'             EA Semi Shangahi Limited           
        byte    "EMBCORF",0'             EMBCORF
        byte    "Shenzhen MicroBT",0'             Shenzhen MicroBT Electronics Technology           
        byte    "Shanghai Simor C",0'             Shanghai Simor Chip Semiconductor Co           
        byte    "Xllbyte",0'             Xllbyte
        byte    "Guangzhou Maidit",0'             Guangzhou Maidite Electronics Co Ltd.           
        byte    "Zhejiang Changch",0'             Zhejiang Changchun Technology Co Ltd           
        byte    "Beijing Cloud Se",0'             Beijing Cloud Security Technology Co Ltd           
        byte    "SSTC Technology ",0'             SSTC Technology and Distribution Inc           
        byte    "Shenzhen Panmin ",0'             Shenzhen Panmin Technology Co Ltd           
        byte    "ITE Tech Inc",0'             ITE Tech Inc
        byte    "Beijing Zettasto",0'             Beijing Zettastone Technology Co Ltd           
        byte    "Powerchip Micro ",0'             Powerchip Micro Device           
        byte    "Shenzhen Ysemi C",0'             Shenzhen Ysemi Computing Co Ltd           
        byte    "Shenzhen Titan M",0'             Shenzhen Titan Micro Electronics Co Ltd           
        byte    "Shenzhen Macrofl",0'             Shenzhen Macroflash Technology Co Ltd           
        byte    "Advantech Group",0'             Advantech Group